const WORD_DATA={};
WORD_DATA.cet4=[
{id:1,en:"abandon",zh:"v. 放弃；抛弃",phonetic:"/əˈbændən/",example:"He abandoned his plan to travel.",pos:"动词",emoji:"🚫"},
{id:2,en:"ability",zh:"n. 能力；才能",phonetic:"/əˈbɪləti/",example:"She has the ability to learn quickly.",pos:"名词",emoji:"💪"},
{id:3,en:"abroad",zh:"ad. 在国外；到国外",phonetic:"/əˈbrɔːd/",example:"He dreams of studying abroad.",pos:"副词",emoji:"✈️"},
{id:4,en:"absent",zh:"a. 缺席的；不在的",phonetic:"/ˈæbsənt/",example:"Tom was absent from school.",pos:"形容词",emoji:"🏃"},
{id:5,en:"absorb",zh:"v. 吸收；吸引注意",phonetic:"/əbˈzɔːb/",example:"Plants absorb water from the soil.",pos:"动词",emoji:"🧽"},
{id:6,en:"abstract",zh:"a. 抽象的 n. 摘要",phonetic:"/ˈæbstrækt/",example:"The concept is too abstract.",pos:"形/名词",emoji:"🎨"},
{id:7,en:"abundant",zh:"a. 丰富的；充裕的",phonetic:"/əˈbʌndənt/",example:"The region has abundant resources.",pos:"形容词",emoji:"🈵"},
{id:8,en:"academic",zh:"a. 学术的；学院的",phonetic:"/ˌækəˈdemɪk/",example:"She has an excellent academic record.",pos:"形容词",emoji:"🎓"},
{id:9,en:"accelerate",zh:"v. 加速；促进",phonetic:"/əkˈseləreɪt/",example:"The car accelerated on the highway.",pos:"动词",emoji:"🚀"},
{id:10,en:"access",zh:"n. 通道；v. 访问",phonetic:"/ˈækses/",example:"Students have access to the library.",pos:"名/动词",emoji:"🔑"},
{id:11,en:"accompany",zh:"v. 陪伴；伴随",phonetic:"/əˈkʌmpəni/",example:"She accompanied her friend.",pos:"动词",emoji:"👫"},
{id:12,en:"accomplish",zh:"v. 完成；实现",phonetic:"/əˈkʌmplɪʃ/",example:"We accomplished our mission.",pos:"动词",emoji:"✅"},
{id:13,en:"account",zh:"n. 账户；说明",phonetic:"/əˈkaʊnt/",example:"He opened a bank account.",pos:"名词",emoji:"🏦"},
{id:14,en:"accurate",zh:"a. 准确的；精确的",phonetic:"/ˈækjərət/",example:"The data must be accurate.",pos:"形容词",emoji:"🎯"},
{id:15,en:"achieve",zh:"v. 达到；取得",phonetic:"/əˈtʃiːv/",example:"She achieved her goal.",pos:"动词",emoji:"🏆"},
{id:16,en:"acknowledge",zh:"v. 承认；确认",phonetic:"/əkˈnɒlɪdʒ/",example:"He acknowledged his mistake.",pos:"动词",emoji:"🙋"},
{id:17,en:"acquire",zh:"v. 获得；习得",phonetic:"/əˈkwaɪər/",example:"It takes time to acquire new skills.",pos:"动词",emoji:"📥"},
{id:18,en:"adapt",zh:"v. 适应；改编",phonetic:"/əˈdæpt/",example:"Animals adapt to their environment.",pos:"动词",emoji:"🦎"},
{id:19,en:"adequate",zh:"a. 足够的；适当的",phonetic:"/ˈædɪkwət/",example:"The supply is adequate.",pos:"形容词",emoji:"✔️"},
{id:20,en:"adjust",zh:"v. 调整；适应",phonetic:"/əˈdʒʌst/",example:"You need to adjust the volume.",pos:"动词",emoji:"⚙️"},
{id:21,en:"admire",zh:"v. 钦佩；赞赏",phonetic:"/ədˈmaɪər/",example:"I admire her courage.",pos:"动词",emoji:"👏"},
{id:22,en:"adopt",zh:"v. 采用；收养",phonetic:"/əˈdɒpt/",example:"They decided to adopt a child.",pos:"动词",emoji:"🤱"},
{id:23,en:"advance",zh:"v./n. 前进；进步",phonetic:"/ədˈvɑːns/",example:"Technology continues to advance.",pos:"动/名词",emoji:"⬆️"},
{id:24,en:"advantage",zh:"n. 优势；有利条件",phonetic:"/ədˈvɑːntɪdʒ/",example:"Being bilingual is an advantage.",pos:"名词",emoji:"👍"},
{id:25,en:"affair",zh:"n. 事件；事务",phonetic:"/əˈfeər/",example:"This is a private affair.",pos:"名词",emoji:"📋"},
{id:26,en:"affect",zh:"v. 影响；感动",phonetic:"/əˈfekt/",example:"The weather affects my mood.",pos:"动词",emoji:"💫"},
{id:27,en:"afford",zh:"v. 负担得起；提供",phonetic:"/əˈfɔːd/",example:"I can't afford a new car.",pos:"动词",emoji:"💰"},
{id:28,en:"aggressive",zh:"a. 侵略的；好斗的",phonetic:"/əˈɡresɪv/",example:"The dog became aggressive.",pos:"形容词",emoji:"😠"},
{id:29,en:"agreement",zh:"n. 协议；一致",phonetic:"/əˈɡriːmənt/",example:"They reached an agreement.",pos:"名词",emoji:"🤝"},
{id:30,en:"agriculture",zh:"n. 农业；农学",phonetic:"/ˈæɡrɪkʌltʃər/",example:"Agriculture is vital for food.",pos:"名词",emoji:"🌾"},
{id:31,en:"alarm",zh:"n. 警报；闹钟",phonetic:"/əˈlɑːm/",example:"The fire alarm went off.",pos:"名词",emoji:"⏰"},
{id:32,en:"alcohol",zh:"n. 酒精；酒",phonetic:"/ˈælkəhɒl/",example:"He doesn't drink alcohol.",pos:"名词",emoji:"🍺"},
{id:33,en:"alter",zh:"v. 改变；修改",phonetic:"/ˈɔːltər/",example:"Nothing can alter the truth.",pos:"动词",emoji:"✏️"},
{id:34,en:"amaze",zh:"v. 使惊奇；使惊愕",phonetic:"/əˈmeɪz/",example:"His talent amazed everyone.",pos:"动词",emoji:"😲"},
{id:35,en:"ambition",zh:"n. 野心；雄心",phonetic:"/æmˈbɪʃn/",example:"She has the ambition to succeed.",pos:"名词",emoji:"🔥"},
{id:36,en:"amount",zh:"n. 数量；金额",phonetic:"/əˈmaʊnt/",example:"A large amount of money.",pos:"名词",emoji:"🔢"},
{id:37,en:"analyze",zh:"v. 分析；解析",phonetic:"/ˈænəlaɪz/",example:"We need to analyze the data.",pos:"动词",emoji:"🔍"},
{id:38,en:"anniversary",zh:"n. 周年纪念日",phonetic:"/ˌænɪˈvɜːsəri/",example:"Today is our anniversary.",pos:"名词",emoji:"🎂"},
{id:39,en:"announce",zh:"v. 宣布；通告",phonetic:"/əˈnaʊns/",example:"The company announced new products.",pos:"动词",emoji:"📣"},
{id:40,en:"annual",zh:"a. 年度的；每年的",phonetic:"/ˈænjuəl/",example:"The annual meeting is next week.",pos:"形容词",emoji:"📅"},
{id:41,en:"anxiety",zh:"n. 焦虑；忧虑",phonetic:"/æŋˈzaɪəti/",example:"She suffers from anxiety.",pos:"名词",emoji:"😰"},
{id:42,en:"apparent",zh:"a. 明显的；表面上的",phonetic:"/əˈpærənt/",example:"It was apparent he was lying.",pos:"形容词",emoji:"👀"},
{id:43,en:"appeal",zh:"v./n. 呼吁；吸引",phonetic:"/əˈpiːl/",example:"The idea appeals to young people.",pos:"动/名词",emoji:"📢"},
{id:44,en:"appetite",zh:"n. 食欲；胃口",phonetic:"/ˈæpɪtaɪt/",example:"Exercise gave her a good appetite.",pos:"名词",emoji:"🍽️"},
{id:45,en:"application",zh:"n. 申请；应用",phonetic:"/ˌæplɪˈkeɪʃn/",example:"I submitted my job application.",pos:"名词",emoji:"📝"},
{id:46,en:"appreciate",zh:"v. 欣赏；感激",phonetic:"/əˈpriːʃieɪt/",example:"I appreciate your help.",pos:"动词",emoji:"🙏"},
{id:47,en:"approach",zh:"v./n. 接近；方法",phonetic:"/əˈprəʊtʃ/",example:"We need a new approach.",pos:"动/名词",emoji:"🚶"},
{id:48,en:"appropriate",zh:"a. 适当的；合适的",phonetic:"/əˈprəʊpriət/",example:"Is this appropriate for work?",pos:"形容词",emoji:"👌"},
{id:49,en:"approve",zh:"v. 批准；赞成",phonetic:"/əˈpruːv/",example:"The plan was approved.",pos:"动词",emoji:"✅"},
{id:50,en:"argue",zh:"v. 争论；辩论",phonetic:"/ˈɑːɡjuː/",example:"They argued about politics.",pos:"动词",emoji:"💬"},
{id:51,en:"arrange",zh:"v. 安排；整理",phonetic:"/əˈreɪndʒ/",example:"She arranged the flowers.",pos:"动词",emoji:"🌺"},
{id:52,en:"artificial",zh:"a. 人工的；人造的",phonetic:"/ˌɑːtɪˈfɪʃl/",example:"Artificial intelligence is advancing.",pos:"形容词",emoji:"🤖"},
{id:53,en:"aspect",zh:"n. 方面；层面",phonetic:"/ˈæspekt/",example:"This aspect is crucial.",pos:"名词",emoji:"🔲"},
{id:54,en:"assemble",zh:"v. 集合；组装",phonetic:"/əˈsembl/",example:"He assembled the furniture.",pos:"动词",emoji:"🔧"},
{id:55,en:"assess",zh:"v. 评估；评定",phonetic:"/əˈses/",example:"Teachers assess progress.",pos:"动词",emoji:"📊"},
{id:56,en:"assign",zh:"v. 分配；指派",phonetic:"/əˈsaɪn/",example:"The task was assigned to me.",pos:"动词",emoji:"📌"},
{id:57,en:"assist",zh:"v. 帮助；协助",phonetic:"/əˈsɪst/",example:"Can I assist you?",pos:"动词",emoji:"🆘"},
{id:58,en:"associate",zh:"v. 联系；关联",phonetic:"/əˈsəʊʃieɪt/",example:"People associate red with danger.",pos:"动词",emoji:"🔗"},
{id:59,en:"assume",zh:"v. 假设；承担",phonetic:"/əˈsjuːm/",example:"Don't assume it will be easy.",pos:"动词",emoji:"🤔"},
{id:60,en:"atmosphere",zh:"n. 气氛；大气层",phonetic:"/ˈætməsfɪər/",example:"The restaurant has a cozy atmosphere.",pos:"名词",emoji:"🌍"},
{id:61,en:"attach",zh:"v. 附上；连接",phonetic:"/əˈtætʃ/",example:"Please attach the file.",pos:"动词",emoji:"📎"},
{id:62,en:"attempt",zh:"v./n. 尝试；企图",phonetic:"/əˈtempt/",example:"He attempted to break the record.",pos:"动/名词",emoji:"🎯"},
{id:63,en:"attend",zh:"v. 出席；参加",phonetic:"/əˈtend/",example:"Will you attend the meeting?",pos:"动词",emoji:"🏫"},
{id:64,en:"attitude",zh:"n. 态度；看法",phonetic:"/ˈætɪtjuːd/",example:"A positive attitude is important.",pos:"名词",emoji:"😊"},
{id:65,en:"attract",zh:"v. 吸引；引起",phonetic:"/əˈtrækt/",example:"The light attracts insects.",pos:"动词",emoji:"🧲"},
{id:66,en:"authority",zh:"n. 权威；当局",phonetic:"/ɔːˈθɒrəti/",example:"The authority issued new rules.",pos:"名词",emoji:"👮"},
{id:67,en:"available",zh:"a. 可用的；有空的",phonetic:"/əˈveɪləbl/",example:"Is this seat available?",pos:"形容词",emoji:"🟢"},
{id:68,en:"average",zh:"n./a. 平均的；普通的",phonetic:"/ˈævərɪdʒ/",example:"The average score was 85.",pos:"名/形容词",emoji:"📈"},
{id:69,en:"avoid",zh:"v. 避免；回避",phonetic:"/əˈvɔɪd/",example:"Try to avoid rush hour.",pos:"动词",emoji:"🚧"},
{id:70,en:"aware",zh:"a. 意识到的；知道的",phonetic:"/əˈweər/",example:"Are you aware of the risks?",pos:"形容词",emoji:"💡"},
{id:71,en:"balance",zh:"n./v. 平衡；余额",phonetic:"/ˈbæləns/",example:"Balance work and life.",pos:"名/动词",emoji:"⚖️"},
{id:72,en:"ban",zh:"v./n. 禁止；禁令",phonetic:"/bæn/",example:"Smoking is banned here.",pos:"动/名词",emoji:"🚫"},
{id:73,en:"barrier",zh:"n. 障碍；屏障",phonetic:"/ˈbæriər/",example:"Language can be a barrier.",pos:"名词",emoji:"🧱"},
{id:74,en:"behalf",zh:"n. 代表；利益",phonetic:"/bɪˈhɑːf/",example:"I speak on behalf of the team.",pos:"名词",emoji:"🗣️"},
{id:75,en:"behave",zh:"v. 行为；表现",phonetic:"/bɪˈheɪv/",example:"Children should behave well.",pos:"动词",emoji:"🧒"},
{id:76,en:"benefit",zh:"n. 利益 v. 有益于",phonetic:"/ˈbenɪfɪt/",example:"Exercise benefits your health.",pos:"名/动词",emoji:"💪"},
{id:77,en:"bitter",zh:"a. 苦的；痛苦的",phonetic:"/ˈbɪtər/",example:"The medicine tastes bitter.",pos:"形容词",emoji:"😖"},
{id:78,en:"blame",zh:"v./n. 责备；责怪",phonetic:"/bleɪm/",example:"Don't blame others.",pos:"动/名词",emoji:"👉"},
{id:79,en:"border",zh:"n. 边界；边境",phonetic:"/ˈbɔːdər/",example:"They crossed the border.",pos:"名词",emoji:"🗺️"},
{id:80,en:"bore",zh:"v. 使厌烦 n. 无聊的人",phonetic:"/bɔːr/",example:"Long speeches bore me.",pos:"动/名词",emoji:"🥱"},
{id:81,en:"brand",zh:"n. 品牌；商标",phonetic:"/brænd/",example:"This brand is popular.",pos:"名词",emoji:"🏷️"},
{id:82,en:"budget",zh:"n. 预算 v. 做预算",phonetic:"/ˈbʌdʒɪt/",example:"We need to budget expenses.",pos:"名/动词",emoji:"💵"},
{id:83,en:"burden",zh:"n. 负担；重担",phonetic:"/ˈbɜːdn/",example:"The debt is a heavy burden.",pos:"名词",emoji:"🏋️"},
{id:84,en:"campaign",zh:"n. 运动；战役",phonetic:"/kæmˈpeɪn/",example:"They launched a campaign.",pos:"名词",emoji:"📣"},
{id:85,en:"capable",zh:"a. 有能力的；能干的",phonetic:"/ˈkeɪpəbl/",example:"She is capable of leading.",pos:"形容词",emoji:"👩‍💼"},
{id:86,en:"capture",zh:"v. 捕获；俘获",phonetic:"/ˈkæptʃər/",example:"She captured the moment.",pos:"动词",emoji:"📸"},
{id:87,en:"career",zh:"n. 职业；生涯",phonetic:"/kəˈrɪər/",example:"She chose teaching as her career.",pos:"名词",emoji:"💼"},
{id:88,en:"category",zh:"n. 类别；种类",phonetic:"/ˈkætəɡəri/",example:"Books are sorted by category.",pos:"名词",emoji:"🗂️"},
{id:89,en:"celebrate",zh:"v. 庆祝；赞美",phonetic:"/ˈselɪbreɪt/",example:"We celebrate New Year.",pos:"动词",emoji:"🎉"},
{id:90,en:"challenge",zh:"n./v. 挑战；质疑",phonetic:"/ˈtʃælɪndʒ/",example:"This is a real challenge.",pos:"名/动词",emoji:"🏔️"},
{id:91,en:"characteristic",zh:"n. 特征 a. 特有的",phonetic:"/ˌkærəktəˈrɪstɪk/",example:"What are its characteristics?",pos:"名/形容词",emoji:"🔬"},
{id:92,en:"circumstance",zh:"n. 环境；情况",phonetic:"/ˈsɜːkəmstəns/",example:"Under no circumstance lie.",pos:"名词",emoji:"🔄"},
{id:93,en:"claim",zh:"v./n. 声称；要求",phonetic:"/kleɪm/",example:"He claims to be innocent.",pos:"动/名词",emoji:"✋"},
{id:94,en:"climate",zh:"n. 气候；风气",phonetic:"/ˈklaɪmət/",example:"Climate change is a global issue.",pos:"名词",emoji:"🌤️"},
{id:95,en:"collapse",zh:"v./n. 倒塌；崩溃",phonetic:"/kəˈlæps/",example:"The building collapsed.",pos:"动/名词",emoji:"💥"},
{id:96,en:"colleague",zh:"n. 同事；同僚",phonetic:"/ˈkɒliːɡ/",example:"I discussed it with my colleague.",pos:"名词",emoji:"👥"},
{id:97,en:"commerce",zh:"n. 商业；贸易",phonetic:"/ˈkɒmɜːs/",example:"E-commerce is growing rapidly.",pos:"名词",emoji:"🛒"},
{id:98,en:"commit",zh:"v. 犯（罪）；承诺",phonetic:"/kəˈmɪt/",example:"He committed a crime.",pos:"动词",emoji:"🤝"},
{id:99,en:"communicate",zh:"v. 交流；沟通",phonetic:"/kəˈmjuːnɪkeɪt/",example:"We communicate by email.",pos:"动词",emoji:"📱"},
{id:100,en:"companion",zh:"n. 同伴；伙伴",phonetic:"/kəmˈpæniən/",example:"A dog is a loyal companion.",pos:"名词",emoji:"🐕"},
{id:101,en:"comparison",zh:"n. 比较；对比",phonetic:"/kəmˈpærɪsn/",example:"In comparison, this is cheaper.",pos:"名词",emoji:"⚖️"},
{id:102,en:"compensate",zh:"v. 补偿；弥补",phonetic:"/ˈkɒmpenseɪt/",example:"Nothing can compensate for lost time.",pos:"动词",emoji:"💱"},
{id:103,en:"compete",zh:"v. 竞争；比赛",phonetic:"/kəmˈpiːt/",example:"Athletes compete for gold.",pos:"动词",emoji:"🏅"},
{id:104,en:"complain",zh:"v. 抱怨；投诉",phonetic:"/kəmˈpleɪn/",example:"He always complains.",pos:"动词",emoji:"😤"},
{id:105,en:"complex",zh:"a. 复杂的 n. 综合体",phonetic:"/ˈkɒmpleks/",example:"The problem is too complex.",pos:"形/名词",emoji:"🧩"},
{id:106,en:"concentrate",zh:"v. 集中；专注",phonetic:"/ˈkɒnsntreɪt/",example:"Concentrate on your studies.",pos:"动词",emoji:"🧠"},
{id:107,en:"concept",zh:"n. 概念；观念",phonetic:"/ˈkɒnsept/",example:"It's a difficult concept.",pos:"名词",emoji:"💭"},
{id:108,en:"concern",zh:"n./v. 关心；担忧",phonetic:"/kənˈsɜːn/",example:"This concerns all of us.",pos:"名/动词",emoji:"😟"},
{id:109,en:"conclude",zh:"v. 得出结论；结束",phonetic:"/kənˈkluːd/",example:"We concluded the meeting.",pos:"动词",emoji:"🏁"},
{id:110,en:"concrete",zh:"a. 具体的 n. 混凝土",phonetic:"/ˈkɒŋkriːt/",example:"Give me a concrete example.",pos:"形/名词",emoji:"🧱"},
{id:111,en:"conduct",zh:"v. 进行；指挥 n. 行为",phonetic:"/kənˈdʌkt/",example:"They conducted a survey.",pos:"动/名词",emoji:"🎼"},
{id:112,en:"conference",zh:"n. 会议；讨论会",phonetic:"/ˈkɒnfərəns/",example:"The conference attracted many.",pos:"名词",emoji:"🎤"},
{id:113,en:"confirm",zh:"v. 确认；证实",phonetic:"/kənˈfɜːm/",example:"Can you confirm the booking?",pos:"动词",emoji:"✔️"},
{id:114,en:"conflict",zh:"n./v. 冲突；矛盾",phonetic:"/ˈkɒnflɪkt/",example:"The conflict lasted for years.",pos:"名/动词",emoji:"💢"},
{id:115,en:"conscious",zh:"a. 有意识的；清醒的",phonetic:"/ˈkɒnʃəs/",example:"He was conscious of the danger.",pos:"形容词",emoji:"👁️"},
{id:116,en:"consequence",zh:"n. 结果；后果",phonetic:"/ˈkɒnsɪkwəns/",example:"Think about the consequences.",pos:"名词",emoji:"⚡"},
{id:117,en:"conservative",zh:"a. 保守的 n. 保守派",phonetic:"/kənˈsɜːvətɪv/",example:"She has a conservative attitude.",pos:"形/名词",emoji:"🛡️"},
{id:118,en:"considerable",zh:"a. 相当大的；可观的",phonetic:"/kənˈsɪdərəbl/",example:"A considerable amount of time.",pos:"形容词",emoji:"📈"},
{id:119,en:"constant",zh:"a. 不变的；持续的",phonetic:"/ˈkɒnstənt/",example:"The constant noise is annoying.",pos:"形容词",emoji:"♾️"},
{id:120,en:"construct",zh:"v. 建造；构造",phonetic:"/kənˈstrʌkt/",example:"They constructed a new bridge.",pos:"动词",emoji:"🏗️"},
{id:121,en:"consume",zh:"v. 消费；消耗",phonetic:"/kənˈsjuːm/",example:"This car consumes less fuel.",pos:"动词",emoji:"⛽"},
{id:122,en:"contact",zh:"n./v. 联系；接触",phonetic:"/ˈkɒntækt/",example:"Please contact me by email.",pos:"名/动词",emoji:"📞"},
{id:123,en:"contain",zh:"v. 包含；容纳",phonetic:"/kənˈteɪn/",example:"The bottle contains water.",pos:"动词",emoji:"🫙"},
{id:124,en:"context",zh:"n. 上下文；背景",phonetic:"/ˈkɒntekst/",example:"You need context to understand.",pos:"名词",emoji:"📄"},
{id:125,en:"contract",zh:"n. 合同 v. 收缩",phonetic:"/ˈkɒntrækt/",example:"They signed a contract.",pos:"名/动词",emoji:"📝"},
{id:126,en:"contribute",zh:"v. 贡献；捐献",phonetic:"/kənˈtrɪbjuːt/",example:"Everyone should contribute.",pos:"动词",emoji:"🤲"},
{id:127,en:"convenient",zh:"a. 方便的；便利的",phonetic:"/kənˈviːniənt/",example:"The location is convenient.",pos:"形容词",emoji:"📍"},
{id:128,en:"convince",zh:"v. 说服；使确信",phonetic:"/kənˈvɪns/",example:"She convinced me to join.",pos:"动词",emoji:"🗣️"},
{id:129,en:"cooperate",zh:"v. 合作；协作",phonetic:"/kəʊˈɒpəreɪt/",example:"Let's cooperate to finish this.",pos:"动词",emoji:"🤝"},
{id:130,en:"crash",zh:"v./n. 碰撞；崩溃",phonetic:"/kræʃ/",example:"The computer crashed.",pos:"动/名词",emoji:"💥"},
{id:131,en:"create",zh:"v. 创造；创建",phonetic:"/kriˈeɪt/",example:"Artists create beautiful works.",pos:"动词",emoji:"✨"},
{id:132,en:"crime",zh:"n. 犯罪；罪行",phonetic:"/kraɪm/",example:"Crime rates have decreased.",pos:"名词",emoji:"🔒"},
{id:133,en:"crisis",zh:"n. 危机；紧要关头",phonetic:"/ˈkraɪsɪs/",example:"The company faced a crisis.",pos:"名词",emoji:"🚨"},
{id:134,en:"critical",zh:"a. 批评的；关键的",phonetic:"/ˈkrɪtɪkl/",example:"This is a critical decision.",pos:"形容词",emoji:"⚠️"},
{id:135,en:"crucial",zh:"a. 至关重要的",phonetic:"/ˈkruːʃl/",example:"Time is crucial in emergencies.",pos:"形容词",emoji:"❗"},
{id:136,en:"cultivate",zh:"v. 培养；耕作",phonetic:"/ˈkʌltɪveɪt/",example:"Cultivate a good habit.",pos:"动词",emoji:"🌱"},
{id:137,en:"curiosity",zh:"n. 好奇心；求知欲",phonetic:"/ˌkjʊəriˈɒsəti/",example:"Curiosity drives discovery.",pos:"名词",emoji:"🐱"},
{id:138,en:"current",zh:"a. 当前的 n. 水流",phonetic:"/ˈkʌrənt/",example:"What is the current situation?",pos:"形/名词",emoji:"⚡"},
{id:139,en:"debate",zh:"n./v. 辩论；争论",phonetic:"/dɪˈbeɪt/",example:"The topic sparked debate.",pos:"名/动词",emoji:"🎤"},
{id:140,en:"decade",zh:"n. 十年",phonetic:"/ˈdekeɪd/",example:"The city changed over a decade.",pos:"名词",emoji:"📅"},
{id:141,en:"decline",zh:"v./n. 下降；拒绝",phonetic:"/dɪˈklaɪn/",example:"Sales declined by 10 percent.",pos:"动/名词",emoji:"📉"},
{id:142,en:"define",zh:"v. 定义；界定",phonetic:"/dɪˈfaɪn/",example:"How do you define happiness?",pos:"动词",emoji:"📖"},
{id:143,en:"deliberate",zh:"a. 故意的；深思熟虑的",phonetic:"/dɪˈlɪbərət/",example:"It was a deliberate decision.",pos:"形容词",emoji:"🤔"},
{id:144,en:"deliver",zh:"v. 递送；发表；分娩",phonetic:"/dɪˈlɪvər/",example:"The package was delivered.",pos:"动词",emoji:"📦"},
{id:145,en:"demand",zh:"n./v. 要求；需求",phonetic:"/dɪˈmɑːnd/",example:"Demand for water is increasing.",pos:"名/动词",emoji:"📈"},
{id:146,en:"demonstrate",zh:"v. 展示；证明",phonetic:"/ˈdemənstreɪt/",example:"He demonstrated the product.",pos:"动词",emoji:"👨‍🏫"},
{id:147,en:"depend",zh:"v. 依赖；取决于",phonetic:"/dɪˈpend/",example:"It depends on the weather.",pos:"动词",emoji:"🔗"},
{id:148,en:"describe",zh:"v. 描述；形容",phonetic:"/dɪˈskraɪb/",example:"Can you describe the suspect?",pos:"动词",emoji:"✍️"},
{id:149,en:"deserve",zh:"v. 值得；应得",phonetic:"/dɪˈzɜːv/",example:"You deserve a reward.",pos:"动词",emoji:"🏆"},
{id:150,en:"desperate",zh:"a. 绝望的；不顾一切的",phonetic:"/ˈdespərət/",example:"He was desperate for help.",pos:"形容词",emoji:"😱"},
{id:151,en:"destination",zh:"n. 目的地；终点",phonetic:"/ˌdestɪˈneɪʃn/",example:"We arrived at our destination.",pos:"名词",emoji:"📍"},
{id:152,en:"determine",zh:"v. 决定；确定",phonetic:"/dɪˈtɜːmɪn/",example:"We need to determine the cause.",pos:"动词",emoji:"🎯"},
{id:153,en:"device",zh:"n. 设备；装置",phonetic:"/dɪˈvaɪs/",example:"This device saves energy.",pos:"名词",emoji:"📱"},
{id:154,en:"devote",zh:"v. 致力于；奉献",phonetic:"/dɪˈvəʊt/",example:"She devoted her life to education.",pos:"动词",emoji:"❤️"},
{id:155,en:"dilemma",zh:"n. 困境；进退两难",phonetic:"/daɪˈlemə/",example:"He faced a moral dilemma.",pos:"名词",emoji:"😖"},
{id:156,en:"discipline",zh:"n. 纪律；学科",phonetic:"/ˈdɪsəplɪn/",example:"Self-discipline is key.",pos:"名词",emoji:"📏"},
{id:157,en:"discount",zh:"n. 折扣 v. 打折",phonetic:"/ˈdɪskaʊnt/",example:"They offered a discount.",pos:"名/动词",emoji:"🏷️"},
{id:158,en:"display",zh:"v./n. 展示；显示",phonetic:"/dɪˈspleɪ/",example:"The works are on display.",pos:"动/名词",emoji:"🖥️"},
{id:159,en:"distinct",zh:"a. 明显的；不同的",phonetic:"/dɪˈstɪŋkt/",example:"There is a distinct smell.",pos:"形容词",emoji:"🔍"},
{id:160,en:"distribute",zh:"v. 分配；分发",phonetic:"/dɪˈstrɪbjuːt/",example:"Food was distributed.",pos:"动词",emoji:"📬"},
{id:161,en:"diverse",zh:"a. 多样的；不同的",phonetic:"/daɪˈvɜːs/",example:"The city has a diverse culture.",pos:"形容词",emoji:"🌈"},
{id:162,en:"document",zh:"n. 文件 v. 记录",phonetic:"/ˈdɒkjumənt/",example:"Please sign this document.",pos:"名/动词",emoji:"📄"},
{id:163,en:"domestic",zh:"a. 国内的；家庭的",phonetic:"/dəˈmestɪk/",example:"Domestic flights are cheaper.",pos:"形容词",emoji:"🏠"},
{id:164,en:"dominate",zh:"v. 支配；统治",phonetic:"/ˈdɒmɪneɪt/",example:"The team dominates the league.",pos:"动词",emoji:"👑"},
{id:165,en:"dramatic",zh:"a. 戏剧性的；巨大的",phonetic:"/drəˈmætɪk/",example:"There was a dramatic change.",pos:"形容词",emoji:"🎭"},
{id:166,en:"economy",zh:"n. 经济；节约",phonetic:"/ɪˈkɒnəmi/",example:"The economy is growing.",pos:"名词",emoji:"📊"},
{id:167,en:"educate",zh:"v. 教育；培养",phonetic:"/ˈedʒukeɪt/",example:"Parents educate their children.",pos:"动词",emoji:"📚"},
{id:168,en:"efficient",zh:"a. 高效的；有效率的",phonetic:"/ɪˈfɪʃnt/",example:"This method is efficient.",pos:"形容词",emoji:"⚡"},
{id:169,en:"eliminate",zh:"v. 消除；淘汰",phonetic:"/ɪˈlɪmɪneɪt/",example:"We must eliminate poverty.",pos:"动词",emoji:"🗑️"},
{id:170,en:"embrace",zh:"v. 拥抱；欣然接受",phonetic:"/ɪmˈbreɪs/",example:"Embrace new challenges.",pos:"动词",emoji:"🤗"},
{id:171,en:"emerge",zh:"v. 出现；浮现",phonetic:"/ɪˈmɜːdʒ/",example:"New evidence emerged.",pos:"动词",emoji:"🌅"},
{id:172,en:"emotion",zh:"n. 情感；情绪",phonetic:"/ɪˈməʊʃn/",example:"She showed no emotion.",pos:"名词",emoji:"❤️"},
{id:173,en:"emphasis",zh:"n. 强调；重点",phonetic:"/ˈemfəsɪs/",example:"The emphasis is on quality.",pos:"名词",emoji:"❗"},
{id:174,en:"employ",zh:"v. 雇用；使用",phonetic:"/ɪmˈplɔɪ/",example:"The company employs 500 people.",pos:"动词",emoji:"👔"},
{id:175,en:"enable",zh:"v. 使能够；启用",phonetic:"/ɪˈneɪbl/",example:"This key enables the function.",pos:"动词",emoji:"🔓"},
{id:176,en:"encounter",zh:"v./n. 遭遇；邂逅",phonetic:"/ɪnˈkaʊntər/",example:"We encountered many problems.",pos:"动/名词",emoji:"⚡"},
{id:177,en:"engage",zh:"v. 从事；吸引；订婚",phonetic:"/ɪnˈɡeɪdʒ/",example:"She is engaged in research.",pos:"动词",emoji:"🔬"},
{id:178,en:"enormous",zh:"a. 巨大的；庞大的",phonetic:"/ɪˈnɔːməs/",example:"The cost is enormous.",pos:"形容词",emoji:"🐘"},
{id:179,en:"ensure",zh:"v. 确保；保证",phonetic:"/ɪnˈʃʊər/",example:"Please ensure the door is locked.",pos:"动词",emoji:"🔒"},
{id:180,en:"enterprise",zh:"n. 企业；事业",phonetic:"/ˈentəpraɪz/",example:"He started his own enterprise.",pos:"名词",emoji:"🏢"},
{id:181,en:"enthusiasm",zh:"n. 热情；热忱",phonetic:"/ɪnˈθjuːziæzəm/",example:"She showed great enthusiasm.",pos:"名词",emoji:"🔥"},
{id:182,en:"environment",zh:"n. 环境",phonetic:"/ɪnˈvaɪrənmənt/",example:"Protect the environment.",pos:"名词",emoji:"🌍"},
{id:183,en:"establish",zh:"v. 建立；设立",phonetic:"/ɪˈstæblɪʃ/",example:"They established a new company.",pos:"动词",emoji:"🏗️"},
{id:184,en:"evaluate",zh:"v. 评价；评估",phonetic:"/ɪˈvæljueɪt/",example:"We need to evaluate the results.",pos:"动词",emoji:"📝"},
{id:185,en:"evidence",zh:"n. 证据；证明",phonetic:"/ˈevɪdəns/",example:"There is no evidence.",pos:"名词",emoji:"🔍"},
{id:186,en:"evolve",zh:"v. 进化；发展",phonetic:"/ɪˈvɒlv/",example:"Species evolve over time.",pos:"动词",emoji:"🧬"},
{id:187,en:"examine",zh:"v. 检查；考试",phonetic:"/ɪɡˈzæmɪn/",example:"The doctor examined the patient.",pos:"动词",emoji:"🔬"},
{id:188,en:"exception",zh:"n. 例外；除外",phonetic:"/ɪkˈsepʃn/",example:"There is no exception.",pos:"名词",emoji:"➖"},
{id:189,en:"exhaust",zh:"v. 使筋疲力尽 n. 废气",phonetic:"/ɪɡˈzɔːst/",example:"The work exhausted me.",pos:"动/名词",emoji:"😫"},
{id:190,en:"expand",zh:"v. 扩展；膨胀",phonetic:"/ɪkˈspænd/",example:"The business is expanding.",pos:"动词",emoji:"🔍"},
{id:191,en:"experiment",zh:"n./v. 实验；试验",phonetic:"/ɪkˈsperɪmənt/",example:"The experiment was successful.",pos:"名/动词",emoji:"🧪"},
{id:192,en:"expert",zh:"n. 专家 a. 熟练的",phonetic:"/ˈekspɜːt/",example:"She is an expert in finance.",pos:"名/形容词",emoji:"👩‍🔬"},
{id:193,en:"export",zh:"v./n. 出口；输出",phonetic:"/ɪkˈspɔːt/",example:"The country exports oil.",pos:"动/名词",emoji:"🚢"},
{id:194,en:"external",zh:"a. 外部的；外界的",phonetic:"/ɪkˈstɜːnl/",example:"External factors affected it.",pos:"形容词",emoji:"🌐"},
{id:195,en:"extraordinary",zh:"a. 非凡的；特别的",phonetic:"/ɪkˈstrɔːdnri/",example:"She has extraordinary talent.",pos:"形容词",emoji:"🌟"},
{id:196,en:"facility",zh:"n. 设施；设备；才能",phonetic:"/fəˈsɪləti/",example:"The sports facility is great.",pos:"名词",emoji:"🏟️"},
{id:197,en:"faith",zh:"n. 信仰；信心",phonetic:"/feɪθ/",example:"Have faith in yourself.",pos:"名词",emoji:"🙏"},
{id:198,en:"feature",zh:"n. 特征；特色 v. 以…为特色",phonetic:"/ˈfiːtʃər/",example:"This phone has many features.",pos:"名/动词",emoji:"✨"},
{id:199,en:"finance",zh:"n. 财政；金融 v. 资助",phonetic:"/ˈfaɪnæns/",example:"He works in finance.",pos:"名/动词",emoji:"💹"},
{id:200,en:"flexible",zh:"a. 灵活的；柔韧的",phonetic:"/ˈfleksəbl/",example:"We need a flexible schedule.",pos:"形容词",emoji:"🤸"}
];
WORD_DATA.cet6=[
{id:1001,en:"abnormal",zh:"a. 反常的；异常的",phonetic:"/æbˈnɔːml/",example:"The weather is abnormal.",pos:"形容词",emoji:"🌡️"},
{id:1002,en:"abolish",zh:"v. 废除；取消",phonetic:"/əˈbɒlɪʃ/",example:"Slavery was abolished.",pos:"动词",emoji:"🚫"},
{id:1003,en:"absurd",zh:"a. 荒谬的；可笑的",phonetic:"/əbˈsɜːd/",example:"The idea sounds absurd.",pos:"形容词",emoji:"🤪"},
{id:1004,en:"accessory",zh:"n. 附件；配件",phonetic:"/əkˈsesəri/",example:"Phone accessories are popular.",pos:"名词",emoji:"📱"},
{id:1005,en:"accommodate",zh:"v. 容纳；提供住宿",phonetic:"/əˈkɒmədeɪt/",example:"The hotel can accommodate 200 guests.",pos:"动词",emoji:"🏨"},
{id:1006,en:"acquaint",zh:"v. 使熟悉；使了解",phonetic:"/əˈkweɪnt/",example:"Let me acquaint you with the facts.",pos:"动词",emoji:"🤝"},
{id:1007,en:"activate",zh:"v. 激活；启动",phonetic:"/ˈæktɪveɪt/",example:"Activate your account now.",pos:"动词",emoji:"▶️"},
{id:1008,en:"acute",zh:"a. 急性的；敏锐的",phonetic:"/əˈkjuːt/",example:"She has acute hearing.",pos:"形容词",emoji:"🔪"},
{id:1009,en:"addict",zh:"n. 上瘾者 v. 使上瘾",phonetic:"/ˈædɪkt/",example:"He is a video game addict.",pos:"名/动词",emoji:"🎮"},
{id:1010,en:"adhere",zh:"v. 坚持；粘附",phonetic:"/ədˈhɪər/",example:"We must adhere to the rules.",pos:"动词",emoji:"🩹"},
{id:1011,en:"adjacent",zh:"a. 邻近的；毗连的",phonetic:"/əˈdʒeɪsnt/",example:"The two rooms are adjacent.",pos:"形容词",emoji:"🏘️"},
{id:1012,en:"administer",zh:"v. 管理；执行",phonetic:"/ədˈmɪnɪstər/",example:"She administers the company.",pos:"动词",emoji:"👩‍💼"},
{id:1013,en:"adolescent",zh:"n. 青少年 a. 青春期的",phonetic:"/ˌædəˈlesnt/",example:"Adolescents need guidance.",pos:"名/形容词",emoji:"🧑"},
{id:1014,en:"adverse",zh:"a. 不利的；相反的",phonetic:"/ˈædvɜːs/",example:"Adverse weather delayed the flight.",pos:"形容词",emoji:"⚠️"},
{id:1015,en:"advocate",zh:"v. 提倡 n. 倡导者",phonetic:"/ˈædvəkeɪt/",example:"She advocates for equal rights.",pos:"动/名词",emoji:"📢"},
{id:1016,en:"aesthetic",zh:"a. 美学的；审美的",phonetic:"/iːsˈθetɪk/",example:"The design has aesthetic appeal.",pos:"形容词",emoji:"🎨"},
{id:1017,en:"affiliate",zh:"v. 使隶属 n. 附属机构",phonetic:"/əˈfɪlieɪt/",example:"The hospital is affiliated with the university.",pos:"动/名词",emoji:"🏥"},
{id:1018,en:"affirm",zh:"v. 肯定；确认",phonetic:"/əˈfɜːm/",example:"He affirmed his commitment.",pos:"动词",emoji:"✅"},
{id:1019,en:"aggravate",zh:"v. 加重；使恶化",phonetic:"/ˈæɡrəveɪt/",example:"Smoking aggravates the condition.",pos:"动词",emoji:"📈"},
{id:1020,en:"aggregate",zh:"n. 合计 a. 总计的",phonetic:"/ˈæɡrɪɡət/",example:"The aggregate score was high.",pos:"名/形容词",emoji:"∑"},
{id:1021,en:"agony",zh:"n. 极大的痛苦",phonetic:"/ˈæɡəni/",example:"He was in agony after the injury.",pos:"名词",emoji:"😫"},
{id:1022,en:"alien",zh:"a. 外国的 n. 外星人",phonetic:"/ˈeɪliən/",example:"The concept seemed alien to him.",pos:"形/名词",emoji:"👽"},
{id:1023,en:"allege",zh:"v. 声称；指控",phonetic:"/əˈledʒ/",example:"He alleged that he was innocent.",pos:"动词",emoji:"⚖️"},
{id:1024,en:"alleviate",zh:"v. 减轻；缓解",phonetic:"/əˈliːvieɪt/",example:"Medicine can alleviate pain.",pos:"动词",emoji:"💊"},
{id:1025,en:"allocate",zh:"v. 分配；拨出",phonetic:"/ˈæləkeɪt/",example:"Funds were allocated for education.",pos:"动词",emoji:"💰"},
{id:1026,en:"alloy",zh:"n. 合金",phonetic:"/ˈælɔɪ/",example:"Steel is an alloy of iron.",pos:"名词",emoji:"🔩"},
{id:1027,en:"allude",zh:"v. 暗示；间接提到",phonetic:"/əˈluːd/",example:"He alluded to the problem.",pos:"动词",emoji:"👀"},
{id:1028,en:"ally",zh:"n. 盟友 v. 结盟",phonetic:"/ˈælaɪ/",example:"The two countries became allies.",pos:"名/动词",emoji:"🤝"},
{id:1029,en:"alternate",zh:"v. 交替 a. 轮流的",phonetic:"/ˈɔːltəneɪt/",example:"Work and rest alternate.",pos:"动/形容词",emoji:"🔄"},
{id:1030,en:"amateur",zh:"n. 业余爱好者 a. 业余的",phonetic:"/ˈæmətər/",example:"He is an amateur photographer.",pos:"名/形容词",emoji:"📷"},
{id:1031,en:"ambiguous",zh:"a. 模糊的；歧义的",phonetic:"/æmˈbɪɡjuəs/",example:"The statement was ambiguous.",pos:"形容词",emoji:"❓"},
{id:1032,en:"amend",zh:"v. 修改；修订",phonetic:"/əˈmend/",example:"They amended the law.",pos:"动词",emoji:"✏️"},
{id:1033,en:"ample",zh:"a. 充足的；宽敞的",phonetic:"/ˈæmpl/",example:"There is ample time to prepare.",pos:"形容词",emoji:"🈵"},
{id:1034,en:"analogy",zh:"n. 类比；相似",phonetic:"/əˈnælədʒi/",example:"He used an analogy to explain.",pos:"名词",emoji:"🔗"},
{id:1035,en:"angel",zh:"n. 天使",phonetic:"/ˈeɪndʒl/",example:"She is like an angel.",pos:"名词",emoji:"👼"},
{id:1036,en:"anonymous",zh:"a. 匿名的；无名的",phonetic:"/əˈnɒnɪməs/",example:"The letter was anonymous.",pos:"形容词",emoji:"🎭"},
{id:1037,en:"apparatus",zh:"n. 设备；仪器",phonetic:"/ˌæpəˈreɪtəs/",example:"The laboratory has modern apparatus.",pos:"名词",emoji:"🔬"},
{id:1038,en:"applaud",zh:"v. 鼓掌；称赞",phonetic:"/əˈplɔːd/",example:"The audience applauded loudly.",pos:"动词",emoji:"👏"},
{id:1039,en:"appraisal",zh:"n. 评价；评估",phonetic:"/əˈpreɪzl/",example:"The manager gave a performance appraisal.",pos:"名词",emoji:"📋"},
{id:1040,en:"apt",zh:"a. 恰当的；有…倾向的",phonetic:"/æpt/",example:"An apt description of the situation.",pos:"形容词",emoji:"🎯"},
{id:1041,en:"arc",zh:"n. 弧；弧形",phonetic:"/ɑːk/",example:"The rainbow formed an arc.",pos:"名词",emoji:"🌈"},
{id:1042,en:"arch",zh:"n. 拱门 v. 拱起",phonetic:"/ɑːtʃ/",example:"The bridge has a stone arch.",pos:"名/动词",emoji:"🌉"},
{id:1043,en:"arena",zh:"n. 竞技场；舞台",phonetic:"/əˈriːnə/",example:"The boxers entered the arena.",pos:"名词",emoji:"🏟️"},
{id:1044,en:"armor",zh:"n. 盔甲；装甲",phonetic:"/ˈɑːmər/",example:"Knights wore heavy armor.",pos:"名词",emoji:"🛡️"},
{id:1045,en:"array",zh:"n. 数组；大量",phonetic:"/əˈreɪ/",example:"An array of options was offered.",pos:"名词",emoji:"📊"},
{id:1046,en:"arrogant",zh:"a. 傲慢的；自大的",phonetic:"/ˈærəɡənt/",example:"He is too arrogant to listen.",pos:"形容词",emoji:"😤"},
{id:1047,en:"articulate",zh:"v. 清楚表达 a. 口齿伶俐的",phonetic:"/ɑːˈtɪkjuleɪt/",example:"She articulated her ideas clearly.",pos:"动/形容词",emoji:"🗣️"},
{id:1048,en:"ascend",zh:"v. 上升；攀登",phonetic:"/əˈsend/",example:"The elevator ascended slowly.",pos:"动词",emoji:"⬆️"},
{id:1049,en:"ascribe",zh:"v. 把…归因于",phonetic:"/əˈskraɪb/",example:"He ascribed his success to luck.",pos:"动词",emoji:"🔍"},
{id:1050,en:"assassination",zh:"n. 暗杀；刺杀",phonetic:"/əˌsæsɪˈneɪʃn/",example:"The assassination shocked the world.",pos:"名词",emoji:"🔫"},
{id:1051,en:"assault",zh:"n./v. 攻击；袭击",phonetic:"/əˈsɔːlt/",example:"He was charged with assault.",pos:"名/动词",emoji:"👊"},
{id:1052,en:"assert",zh:"v. 断言；主张",phonetic:"/əˈsɜːt/",example:"He asserted his innocence.",pos:"动词",emoji:"💪"},
{id:1053,en:"asset",zh:"n. 资产；优点",phonetic:"/ˈæset/",example:"Good health is a valuable asset.",pos:"名词",emoji:"💎"},
{id:1054,en:"assimilate",zh:"v. 吸收；同化",phonetic:"/əˈsɪməleɪt/",example:"Immigrants assimilate into society.",pos:"动词",emoji:"🔄"},
{id:1055,en:"asthma",zh:"n. 哮喘",phonetic:"/ˈæsmə/",example:"He suffers from asthma.",pos:"名词",emoji:"😤"},
{id:1056,en:"astronomy",zh:"n. 天文学",phonetic:"/əˈstrɒnəmi/",example:"Astronomy is the study of stars.",pos:"名词",emoji:"🔭"},
{id:1057,en:"athlete",zh:"n. 运动员",phonetic:"/ˈæθliːt/",example:"She is a professional athlete.",pos:"名词",emoji:"🏃"},
{id:1058,en:"atlas",zh:"n. 地图集",phonetic:"/ˈætləs/",example:"Look it up in the atlas.",pos:"名词",emoji:"🗺️"},
{id:1059,en:"attain",zh:"v. 达到；获得",phonetic:"/əˈteɪn/",example:"He attained his goal at last.",pos:"动词",emoji:"🎯"},
{id:1060,en:"attendance",zh:"n. 出席；参加",phonetic:"/əˈtendəns/",example:"Attendance is mandatory.",pos:"名词",emoji:"📋"},
{id:1061,en:"attorney",zh:"n. 律师",phonetic:"/əˈtɜːni/",example:"He hired an attorney.",pos:"名词",emoji:"⚖️"},
{id:1062,en:"attribute",zh:"v. 把…归因于 n. 属性",phonetic:"/əˈtrɪbjuːt/",example:"She attributes her success to hard work.",pos:"动/名词",emoji:"🔖"},
{id:1063,en:"auction",zh:"n./v. 拍卖",phonetic:"/ˈɔːkʃn/",example:"The painting was sold at auction.",pos:"名/动词",emoji:"🔨"},
{id:1064,en:"authentic",zh:"a. 真正的；可靠的",phonetic:"/ɔːˈθentɪk/",example:"Is this an authentic signature?",pos:"形容词",emoji:"✅"},
{id:1065,en:"authorize",zh:"v. 授权；批准",phonetic:"/ˈɔːθəraɪz/",example:"The manager authorized the payment.",pos:"动词",emoji:"✍️"},
{id:1066,en:"automate",zh:"v. 自动化",phonetic:"/ˈɔːtəmeɪt/",example:"The factory is fully automated.",pos:"动词",emoji:"🤖"},
{id:1067,en:"autonomy",zh:"n. 自治；自主权",phonetic:"/ɔːˈtɒnəmi/",example:"The region wants more autonomy.",pos:"名词",emoji:"🏳️"},
{id:1068,en:"avail",zh:"v. 有用 n. 效用",phonetic:"/əˈveɪl/",example:"All efforts availed nothing.",pos:"动/名词",emoji:"🔧"},
{id:1069,en:"avert",zh:"v. 避免；转移",phonetic:"/əˈvɜːt/",example:"He averted his eyes from the scene.",pos:"动词",emoji:"🔄"},
{id:1070,en:"aviation",zh:"n. 航空；飞行",phonetic:"/ˌeɪviˈeɪʃn/",example:"Aviation has changed the world.",pos:"名词",emoji:"✈️"},
{id:1071,en:"axis",zh:"n. 轴；轴线",phonetic:"/ˈæksɪs/",example:"The Earth rotates on its axis.",pos:"名词",emoji:"🌍"},
{id:1072,en:"bachelor",zh:"n. 学士；单身汉",phonetic:"/ˈbætʃələr/",example:"He has a bachelor's degree.",pos:"名词",emoji:"🎓"},
{id:1073,en:"baffle",zh:"v. 使困惑 n. 挡板",phonetic:"/ˈbæfl/",example:"The mystery baffled the police.",pos:"动词",emoji:"🤔"},
{id:1074,en:"bald",zh:"a. 秃头的；光秃的",phonetic:"/bɔːld/",example:"He is going bald.",pos:"形容词",emoji:"👨‍🦲"},
{id:1075,en:"bankrupt",zh:"a./v./n. 破产",phonetic:"/ˈbæŋkrʌpt/",example:"The company went bankrupt.",pos:"形/动/名",emoji:"💸"},
{id:1076,en:"barren",zh:"a. 贫瘠的；不生育的",phonetic:"/ˈbærən/",example:"The land is barren.",pos:"形容词",emoji:"🏜️"},
{id:1077,en:"batch",zh:"n. 一批；一组",phonetic:"/bætʃ/",example:"The first batch of students arrived.",pos:"名词",emoji:"📦"},
{id:1078,en:"bearing",zh:"n. 关系；方位；轴承",phonetic:"/ˈbeərɪŋ/",example:"That has no bearing on the case.",pos:"名词",emoji:"🧭"},
{id:1079,en:"beforehand",zh:"ad. 预先；事先",phonetic:"/bɪˈfɔːhænd/",example:"Please let me know beforehand.",pos:"副词",emoji:"⏰"},
{id:1080,en:"betray",zh:"v. 背叛；出卖",phonetic:"/bɪˈtreɪ/",example:"He betrayed his friend's trust.",pos:"动词",emoji:"💔"},
{id:1081,en:"bewilder",zh:"v. 使迷惑；使糊涂",phonetic:"/bɪˈwɪldər/",example:"The instructions bewildered me.",pos:"动词",emoji:"😵"},
{id:1082,en:"bias",zh:"n. 偏见 v. 使有偏见",phonetic:"/ˈbaɪəs/",example:"The judge showed no bias.",pos:"名/动词",emoji:"⚖️"},
{id:1083,en:"biography",zh:"n. 传记",phonetic:"/baɪˈɒɡrəfi/",example:"She wrote a biography of Lincoln.",pos:"名词",emoji:"📖"},
{id:1084,en:"bizarre",zh:"a. 奇异的；古怪的",phonetic:"/bɪˈzɑːr/",example:"That's a bizarre coincidence.",pos:"形容词",emoji:"🤪"},
{id:1085,en:"blaze",zh:"n. 火焰；光辉 v. 燃烧",phonetic:"/bleɪz/",example:"The fire blazed through the night.",pos:"名/动词",emoji:"🔥"},
{id:1086,en:"bleak",zh:"a. 荒凉的；黯淡的",phonetic:"/bliːk/",example:"The future looks bleak.",pos:"形容词",emoji:"🌫️"},
{id:1087,en:"bless",zh:"v. 祝福；保佑",phonetic:"/bles/",example:"God bless you.",pos:"动词",emoji:"🙏"},
{id:1088,en:"blossom",zh:"n. 花 v. 开花；发展",phonetic:"/ˈblɒsəm/",example:"The cherry trees are in blossom.",pos:"名/动词",emoji:"🌸"},
{id:1089,en:"blunder",zh:"n. 大错 v. 犯大错",phonetic:"/ˈblʌndər/",example:"He made a serious blunder.",pos:"名/动词",emoji:"💥"},
{id:1090,en:"blunt",zh:"a. 钝的；直率的",phonetic:"/blʌnt/",example:"Let me be blunt with you.",pos:"形容词",emoji:"🗡️"},
{id:1091,en:"blush",zh:"v./n. 脸红",phonetic:"/blʌʃ/",example:"She blushed at the compliment.",pos:"动/名词",emoji:"😊"},
{id:1092,en:"bonus",zh:"n. 奖金；额外好处",phonetic:"/ˈbəʊnəs/",example:"He received a year-end bonus.",pos:"名词",emoji:"💵"},
{id:1093,en:"boom",zh:"n./v. 繁荣；激增",phonetic:"/buːm/",example:"The economy is booming.",pos:"名/动词",emoji:"📈"},
{id:1094,en:"boost",zh:"v./n. 促进；提高",phonetic:"/buːst/",example:"The win boosted our confidence.",pos:"动/名词",emoji:"🚀"},
{id:1095,en:"boycott",zh:"v./n. 抵制",phonetic:"/ˈbɔɪkɒt/",example:"They boycotted the products.",pos:"动/名词",emoji:"✋"},
{id:1096,en:"breach",zh:"n./v. 违反；破坏",phonetic:"/briːtʃ/",example:"This is a breach of contract.",pos:"名/动词",emoji:"💔"},
{id:1097,en:"breakdown",zh:"n. 故障；崩溃",phonetic:"/ˈbreɪkdaʊn/",example:"The car had a breakdown.",pos:"名词",emoji:"🔧"},
{id:1098,en:"brew",zh:"v. 酿造；酝酿",phonetic:"/bruː/",example:"He brews his own beer.",pos:"动词",emoji:"🍺"},
{id:1099,en:"brink",zh:"n. 边缘",phonetic:"/brɪŋk/",example:"We are on the brink of disaster.",pos:"名词",emoji:"⚡"},
{id:1100,en:"brisk",zh:"a. 轻快的；兴隆的",phonetic:"/brɪsk/",example:"They went for a brisk walk.",pos:"形容词",emoji:"🚶"}
];
WORD_DATA.postgrad=[
{id:2001,en:"alleviate",zh:"v. 减轻；缓解",phonetic:"/əˈliːvieɪt/",example:"Medicine can alleviate pain.",pos:"动词",emoji:"💊"},
{id:2002,en:"ambiguous",zh:"a. 模糊的；歧义的",phonetic:"/æmˈbɪɡjuəs/",example:"The statement was ambiguous.",pos:"形容词",emoji:"❓"},
{id:2003,en:"anonymous",zh:"a. 匿名的；无名的",phonetic:"/əˈnɒnɪməs/",example:"The donation was anonymous.",pos:"形容词",emoji:"🎭"},
{id:2004,en:"articulate",zh:"v. 清楚表达 a. 口齿伶俐的",phonetic:"/ɑːˈtɪkjuleɪt/",example:"She articulated her ideas clearly.",pos:"动/形容词",emoji:"🗣️"},
{id:2005,en:"ascertain",zh:"v. 确定；查明",phonetic:"/ˌæsəˈteɪn/",example:"We must ascertain the facts.",pos:"动词",emoji:"🔍"},
{id:2006,en:"aspire",zh:"v. 渴望；有志于",phonetic:"/əˈspaɪər/",example:"She aspires to be a doctor.",pos:"动词",emoji:"🌟"},
{id:2007,en:"assault",zh:"n./v. 攻击；袭击",phonetic:"/əˈsɔːlt/",example:"He was charged with assault.",pos:"名/动词",emoji:"👊"},
{id:2008,en:"asset",zh:"n. 资产；优点",phonetic:"/ˈæset/",example:"Good health is a valuable asset.",pos:"名词",emoji:"💎"},
{id:2009,en:"attain",zh:"v. 达到；获得",phonetic:"/əˈteɪn/",example:"He attained his goal at last.",pos:"动词",emoji:"🎯"},
{id:2010,en:"audit",zh:"n./v. 审计；审查",phonetic:"/ˈɔːdɪt/",example:"The company is under audit.",pos:"名/动词",emoji:"📋"},
{id:2011,en:"augment",zh:"v. 增加；增大",phonetic:"/ɔːɡˈment/",example:"He augmented his income by freelancing.",pos:"动词",emoji:"📈"},
{id:2012,en:"autonomous",zh:"a. 自治的；自主的",phonetic:"/ɔːˈtɒnəməs/",example:"The region is autonomous.",pos:"形容词",emoji:"🏳️"},
{id:2013,en:"aversion",zh:"n. 厌恶；反感",phonetic:"/əˈvɜːʃn/",example:"She has an aversion to smoking.",pos:"名词",emoji:"😖"},
{id:2014,en:"barren",zh:"a. 贫瘠的；不生育的",phonetic:"/ˈbærən/",example:"The land is barren.",pos:"形容词",emoji:"🏜️"},
{id:2015,en:"benevolent",zh:"a. 仁慈的；善意的",phonetic:"/bəˈnevələnt/",example:"A benevolent smile crossed her face.",pos:"形容词",emoji:"😊"},
{id:2016,en:"bias",zh:"n. 偏见 v. 使有偏见",phonetic:"/ˈbaɪəs/",example:"The judge showed no bias.",pos:"名/动词",emoji:"⚖️"},
{id:2017,en:"bizarre",zh:"a. 奇异的；古怪的",phonetic:"/bɪˈzɑːr/",example:"That's a bizarre coincidence.",pos:"形容词",emoji:"🤪"},
{id:2018,en:"bleak",zh:"a. 荒凉的；黯淡的",phonetic:"/bliːk/",example:"The future looks bleak.",pos:"形容词",emoji:"🌫️"},
{id:2019,en:"blunder",zh:"n. 大错 v. 犯大错",phonetic:"/ˈblʌndər/",example:"He made a serious blunder.",pos:"名/动词",emoji:"💥"},
{id:2020,en:"breach",zh:"n./v. 违反；破坏",phonetic:"/briːtʃ/",example:"This is a breach of contract.",pos:"名/动词",emoji:"💔"},
{id:2021,en:"bureaucracy",zh:"n. 官僚机构；官僚主义",phonetic:"/bjʊəˈrɒkrəsi/",example:"The bureaucracy slows things down.",pos:"名词",emoji:"🏛️"},
{id:2022,en:"catastrophe",zh:"n. 大灾难；灾祸",phonetic:"/kəˈtæstrəfi/",example:"The flood was a catastrophe.",pos:"名词",emoji:"🌊"},
{id:2023,en:"chronic",zh:"a. 慢性的；长期的",phonetic:"/ˈkrɒnɪk/",example:"He has chronic back pain.",pos:"形容词",emoji:"🩺"},
{id:2024,en:"coalition",zh:"n. 联盟；联合",phonetic:"/ˌkəʊəˈlɪʃn/",example:"They formed a coalition government.",pos:"名词",emoji:"🤝"},
{id:2025,en:"cognitive",zh:"a. 认知的；认识的",phonetic:"/ˈkɒɡnətɪv/",example:"Cognitive abilities decline with age.",pos:"形容词",emoji:"🧠"},
{id:2026,en:"coherent",zh:"a. 连贯的；一致的",phonetic:"/kəʊˈhɪərənt/",example:"His argument was not coherent.",pos:"形容词",emoji:"🔗"},
{id:2027,en:"commence",zh:"v. 开始；着手",phonetic:"/kəˈmens/",example:"The ceremony will commence at noon.",pos:"动词",emoji:"▶️"},
{id:2028,en:"commodity",zh:"n. 商品；日用品",phonetic:"/kəˈmɒdəti/",example:"Oil is a valuable commodity.",pos:"名词",emoji:"🛢️"},
{id:2029,en:"compassion",zh:"n. 同情；怜悯",phonetic:"/kəmˈpæʃn/",example:"Show compassion for the poor.",pos:"名词",emoji:"❤️"},
{id:2030,en:"comply",zh:"v. 遵守；服从",phonetic:"/kəmˈplaɪ/",example:"Everyone must comply with the rules.",pos:"动词",emoji:"✅"},
{id:2031,en:"comprehensive",zh:"a. 全面的；综合的",phonetic:"/ˌkɒmprɪˈhensɪv/",example:"A comprehensive review is needed.",pos:"形容词",emoji:"📚"},
{id:2032,en:"conceive",zh:"v. 构想；怀孕",phonetic:"/kənˈsiːv/",example:"She conceived a brilliant idea.",pos:"动词",emoji:"💡"},
{id:2033,en:"conception",zh:"n. 概念；构思；怀孕",phonetic:"/kənˈsepʃn/",example:"The conception of the project took years.",pos:"名词",emoji:"🤰"},
{id:2034,en:"conscience",zh:"n. 良心；良知",phonetic:"/ˈkɒnʃəns/",example:"Let your conscience be your guide.",pos:"名词",emoji:"⚖️"},
{id:2035,en:"consolidate",zh:"v. 巩固；合并",phonetic:"/kənˈsɒlɪdeɪt/",example:"We need to consolidate our position.",pos:"动词",emoji:"🧱"},
{id:2036,en:"conspiracy",zh:"n. 阴谋；共谋",phonetic:"/kənˈspɪrəsi/",example:"They uncovered a conspiracy.",pos:"名词",emoji:"🕵️"},
{id:2037,en:"constitute",zh:"v. 构成；组成",phonetic:"/ˈkɒnstɪtjuːt/",example:"Women constitute 51% of the population.",pos:"动词",emoji:"🧩"},
{id:2038,en:"contemplate",zh:"v. 沉思；考虑",phonetic:"/ˈkɒntəmpleɪt/",example:"He contemplated his future.",pos:"动词",emoji:"🤔"},
{id:2039,en:"contempt",zh:"n. 轻视；蔑视",phonetic:"/kənˈtempt/",example:"He looked at me with contempt.",pos:"名词",emoji:"😒"},
{id:2040,en:"contend",zh:"v. 竞争；主张",phonetic:"/kənˈtend/",example:"Several teams contend for the title.",pos:"动词",emoji:"🥊"},
{id:2041,en:"converge",zh:"v. 汇聚；集中",phonetic:"/kənˈvɜːdʒ/",example:"The roads converge at the square.",pos:"动词",emoji:"🎯"},
{id:2042,en:"convict",zh:"v. 定罪 n. 罪犯",phonetic:"/kənˈvɪkt/",example:"He was convicted of theft.",pos:"动/名词",emoji:"⚖️"},
{id:2043,en:"cordial",zh:"a. 热忱的；友好的",phonetic:"/ˈkɔːdiəl/",example:"They had a cordial meeting.",pos:"形容词",emoji:"🤝"},
{id:2044,en:"correlate",zh:"v. 相关；关联",phonetic:"/ˈkɒrəleɪt/",example:"Smoking correlates with cancer.",pos:"动词",emoji:"📊"},
{id:2045,en:"corrode",zh:"v. 腐蚀；侵蚀",phonetic:"/kəˈrəʊd/",example:"Rust corrodes iron.",pos:"动词",emoji:"🪛"},
{id:2046,en:"counsel",zh:"n./v. 劝告；律师",phonetic:"/ˈkaʊnsl/",example:"He gave me good counsel.",pos:"名/动词",emoji:"💼"},
{id:2047,en:"counterpart",zh:"n. 对应的人或物",phonetic:"/ˈkaʊntəpɑːt/",example:"The CEO met his foreign counterpart.",pos:"名词",emoji:"👥"},
{id:2048,en:"criterion",zh:"n. 标准；准则",phonetic:"/kraɪˈtɪəriən/",example:"What is the criterion for success?",pos:"名词",emoji:"📏"},
{id:2049,en:"cynical",zh:"a. 愤世嫉俗的；怀疑的",phonetic:"/ˈsɪnɪkl/",example:"He has a cynical view of politics.",pos:"形容词",emoji:"🙄"},
{id:2050,en:"decisive",zh:"a. 决定性的；果断的",phonetic:"/dɪˈsaɪsɪv/",example:"It was a decisive victory.",pos:"形容词",emoji:"🎯"},
{id:2051,en:"dedicate",zh:"v. 奉献；献身于",phonetic:"/ˈdedɪkeɪt/",example:"She dedicated her life to science.",pos:"动词",emoji:"❤️"},
{id:2052,en:"deem",zh:"v. 认为；视为",phonetic:"/diːm/",example:"They deemed it necessary.",pos:"动词",emoji:"💭"},
{id:2053,en:"defy",zh:"v. 违抗；挑战",phonetic:"/dɪˈfaɪ/",example:"The beauty defies description.",pos:"动词",emoji:"✊"},
{id:2054,en:"denounce",zh:"v. 谴责；告发",phonetic:"/dɪˈnaʊns/",example:"They denounced the violence.",pos:"动词",emoji:"🗣️"},
{id:2055,en:"depict",zh:"v. 描绘；描述",phonetic:"/dɪˈpɪkt/",example:"The painting depicts a battle.",pos:"动词",emoji:"🎨"},
{id:2056,en:"deteriorate",zh:"v. 恶化；变坏",phonetic:"/dɪˈtɪəriəreɪt/",example:"His health deteriorated.",pos:"动词",emoji:"📉"},
{id:2057,en:"diligent",zh:"a. 勤奋的；用功的",phonetic:"/ˈdɪlɪdʒənt/",example:"She is a diligent student.",pos:"形容词",emoji:"📚"},
{id:2058,en:"diminish",zh:"v. 减少；缩小",phonetic:"/dɪˈmɪnɪʃ/",example:"His influence diminished over time.",pos:"动词",emoji:"📉"},
{id:2059,en:"disclose",zh:"v. 揭露；透露",phonetic:"/dɪsˈkləʊz/",example:"He refused to disclose the information.",pos:"动词",emoji:"🔓"},
{id:2060,en:"discrepancy",zh:"n. 差异；不一致",phonetic:"/dɪsˈkrepənsi/",example:"There is a discrepancy in the accounts.",pos:"名词",emoji:"⚠️"},
{id:2061,en:"disperse",zh:"v. 分散；驱散",phonetic:"/dɪˈspɜːs/",example:"The crowd dispersed.",pos:"动词",emoji:"💨"},
{id:2062,en:"dispute",zh:"n./v. 争论；纠纷",phonetic:"/dɪˈspjuːt/",example:"They settled the dispute peacefully.",pos:"名/动词",emoji:"⚡"},
{id:2063,en:"dissolve",zh:"v. 溶解；解散",phonetic:"/dɪˈzɒlv/",example:"Sugar dissolves in water.",pos:"动词",emoji:"💧"},
{id:2064,en:"distort",zh:"v. 扭曲；歪曲",phonetic:"/dɪˈstɔːt/",example:"The mirror distorted my image.",pos:"动词",emoji:"🌀"},
{id:2065,en:"district",zh:"n. 地区；区域",phonetic:"/ˈdɪstrɪkt/",example:"The business district is busy.",pos:"名词",emoji:"🏙️"},
{id:2066,en:"diversion",zh:"n. 转移；消遣",phonetic:"/daɪˈvɜːʃn/",example:"Watching movies is a pleasant diversion.",pos:"名词",emoji:"🎬"},
{id:2067,en:"dividend",zh:"n. 红利；股息",phonetic:"/ˈdɪvɪdend/",example:"The company paid high dividends.",pos:"名词",emoji:"💰"},
{id:2068,en:"doctrine",zh:"n. 教义；学说",phonetic:"/ˈdɒktrɪn/",example:"The doctrine of evolution is widely accepted.",pos:"名词",emoji:"📜"},
{id:2069,en:"domain",zh:"n. 领域；范围",phonetic:"/dəˈmeɪn/",example:"That is outside my domain of expertise.",pos:"名词",emoji:"🌐"},
{id:2070,en:"drought",zh:"n. 干旱；旱灾",phonetic:"/draʊt/",example:"The drought lasted for months.",pos:"名词",emoji:"☀️"},
{id:2071,en:"dubious",zh:"a. 可疑的；不确定的",phonetic:"/ˈdjuːbiəs/",example:"The evidence is dubious.",pos:"形容词",emoji:"🤨"},
{id:2072,en:"duplicate",zh:"v. 复制 n. 副本",phonetic:"/ˈdjuːplɪkeɪt/",example:"Please duplicate this document.",pos:"动/名词",emoji:"📄"},
{id:2073,en:"dwell",zh:"v. 居住；详述",phonetic:"/dwel/",example:"Don't dwell on the past.",pos:"动词",emoji:"🏠"},
{id:2074,en:"eccentric",zh:"a. 古怪的 n. 怪人",phonetic:"/ɪkˈsentrɪk/",example:"He is an eccentric old man.",pos:"形/名词",emoji:"🤪"},
{id:2075,en:"elaborate",zh:"a. 精心制作的 v. 详细阐述",phonetic:"/ɪˈlæbərət/",example:"She elaborated on her plan.",pos:"形/动词",emoji:"📝"},
{id:2076,en:"elegant",zh:"a. 优雅的；精致的",phonetic:"/ˈelɪɡənt/",example:"She wore an elegant dress.",pos:"形容词",emoji:"👗"},
{id:2077,en:"eligible",zh:"a. 有资格的；合格的",phonetic:"/ˈelɪdʒəbl/",example:"Are you eligible to vote?",pos:"形容词",emoji:"✅"},
{id:2078,en:"eloquent",zh:"a. 雄辩的；有口才的",phonetic:"/ˈeləkwənt/",example:"She gave an eloquent speech.",pos:"形容词",emoji:"🎤"},
{id:2079,en:"embark",zh:"v. 上船；开始从事",phonetic:"/ɪmˈbɑːk/",example:"They embarked on a new journey.",pos:"动词",emoji:"🚢"},
{id:2080,en:"empirical",zh:"a. 经验主义的；以观察为依据的",phonetic:"/ɪmˈpɪrɪkl/",example:"This theory needs empirical evidence.",pos:"形容词",emoji:"🔬"},
{id:2081,en:"endeavor",zh:"v./n. 努力；尽力",phonetic:"/ɪnˈdevər/",example:"We endeavor to improve.",pos:"动/名词",emoji:"💪"},
{id:2082,en:"endow",zh:"v. 赋予；捐赠",phonetic:"/ɪnˈdaʊ/",example:"Nature endowed her with beauty.",pos:"动词",emoji:"🎁"},
{id:2083,en:"endure",zh:"v. 忍受；持续",phonetic:"/ɪnˈdjʊər/",example:"I can't endure the pain.",pos:"动词",emoji:"💪"},
{id:2084,en:"entail",zh:"v. 需要；必然导致",phonetic:"/ɪnˈteɪl/",example:"The job entails working weekends.",pos:"动词",emoji:"🔗"},
{id:2085,en:"entity",zh:"n. 实体；存在",phonetic:"/ˈentəti/",example:"The company is a legal entity.",pos:"名词",emoji:"🏢"},
{id:2086,en:"entrepreneur",zh:"n. 企业家",phonetic:"/ˌɒntrəprəˈnɜːr/",example:"He is a successful entrepreneur.",pos:"名词",emoji:"💼"},
{id:2087,en:"envisage",zh:"v. 设想；展望",phonetic:"/ɪnˈvɪzɪdʒ/",example:"I envisage a bright future.",pos:"动词",emoji:"🔮"},
{id:2088,en:"epidemic",zh:"n. 流行病 a. 流行的",phonetic:"/ˌepɪˈdemɪk/",example:"An epidemic broke out in the city.",pos:"名/形容词",emoji:"🦠"},
{id:2089,en:"equity",zh:"n. 公平；公正；股权",phonetic:"/ˈekwəti/",example:"Equity in education is important.",pos:"名词",emoji:"⚖️"},
{id:2090,en:"erosion",zh:"n. 侵蚀；腐蚀",phonetic:"/ɪˈrəʊʒn/",example:"Soil erosion is a serious problem.",pos:"名词",emoji:"🌊"},
{id:2091,en:"essence",zh:"n. 本质；精华",phonetic:"/ˈesns/",example:"The essence of the problem is trust.",pos:"名词",emoji:"💎"},
{id:2092,en:"esteem",zh:"n./v. 尊重；尊敬",phonetic:"/ɪˈstiːm/",example:"She is held in high esteem.",pos:"名/动词",emoji:"🙏"},
{id:2093,en:"ethical",zh:"a. 伦理的；道德的",phonetic:"/ˈeθɪkl/",example:"Is animal testing ethical?",pos:"形容词",emoji:"⚖️"},
{id:2094,en:"ethnic",zh:"a. 种族的；民族的",phonetic:"/ˈeθnɪk/",example:"The city has diverse ethnic groups.",pos:"形容词",emoji:"🌍"},
{id:2095,en:"exempt",zh:"v./a. 免除；豁免",phonetic:"/ɪɡˈzempt/",example:"Students are exempt from the tax.",pos:"动/形容词",emoji:"✂️"},
{id:2096,en:"exile",zh:"n./v. 流放；放逐",phonetic:"/ˈeksaɪl/",example:"He lived in exile for years.",pos:"名/动词",emoji:"🚶"},
{id:2097,en:"exotic",zh:"a. 异国情调的；外来的",phonetic:"/ɪɡˈzɒtɪk/",example:"We tried some exotic food.",pos:"形容词",emoji:"🌴"},
{id:2098,en:"expedition",zh:"n. 远征；探险队",phonetic:"/ˌekspəˈdɪʃn/",example:"They went on an expedition to the Arctic.",pos:"名词",emoji:"🧭"},
{id:2099,en:"expend",zh:"v. 花费；消耗",phonetic:"/ɪkˈspend/",example:"The project expended a lot of time.",pos:"动词",emoji:"💸"},
{id:2100,en:"expire",zh:"v. 到期；终止",phonetic:"/ɪkˈspaɪər/",example:"My passport expires next month.",pos:"动词",emoji:"⏰"}
];
WORD_DATA.daily=[
{id:3001,en:"hello",zh:"int. 你好",phonetic:"/həˈləʊ/",example:"Hello, how are you?",pos:"感叹词",emoji:"👋"},
{id:3002,en:"goodbye",zh:"int. 再见",phonetic:"/ɡʊdˈbaɪ/",example:"Goodbye, see you tomorrow!",pos:"感叹词",emoji:"👋"},
{id:3003,en:"thank",zh:"v. 感谢",phonetic:"/θæŋk/",example:"Thank you for your help.",pos:"动词",emoji:"🙏"},
{id:3004,en:"please",zh:"ad. 请",phonetic:"/pliːz/",example:"Please sit down.",pos:"副词",emoji:"😊"},
{id:3005,en:"sorry",zh:"a. 抱歉的",phonetic:"/ˈsɒri/",example:"I'm sorry for being late.",pos:"形容词",emoji:"😔"},
{id:3006,en:"welcome",zh:"v./n. 欢迎",phonetic:"/ˈwelkəm/",example:"Welcome to our home.",pos:"动/名词",emoji:"🎉"},
{id:3007,en:"morning",zh:"n. 早晨",phonetic:"/ˈmɔːnɪŋ/",example:"Good morning, everyone!",pos:"名词",emoji:"🌅"},
{id:3008,en:"evening",zh:"n. 晚上",phonetic:"/ˈiːvnɪŋ/",example:"Good evening, ladies and gentlemen.",pos:"名词",emoji:"🌆"},
{id:3009,en:"friend",zh:"n. 朋友",phonetic:"/frend/",example:"She is my best friend.",pos:"名词",emoji:"👫"},
{id:3010,en:"family",zh:"n. 家庭",phonetic:"/ˈfæməli/",example:"Family is very important.",pos:"名词",emoji:"👨‍👩‍👧‍👦"},
{id:3011,en:"happy",zh:"a. 快乐的",phonetic:"/ˈhæpi/",example:"I'm so happy today!",pos:"形容词",emoji:"😄"},
{id:3012,en:"beautiful",zh:"a. 美丽的",phonetic:"/ˈbjuːtɪfl/",example:"What a beautiful sunset!",pos:"形容词",emoji:"🌅"},
{id:3013,en:"delicious",zh:"a. 美味的",phonetic:"/dɪˈlɪʃəs/",example:"This cake is delicious.",pos:"形容词",emoji:"🍰"},
{id:3014,en:"important",zh:"a. 重要的",phonetic:"/ɪmˈpɔːtnt/",example:"This is a very important meeting.",pos:"形容词",emoji:"❗"},
{id:3015,en:"interesting",zh:"a. 有趣的",phonetic:"/ˈɪntrəstɪŋ/",example:"That's an interesting idea.",pos:"形容词",emoji:"🤔"},
{id:3016,en:"wonderful",zh:"a. 精彩的；极好的",phonetic:"/ˈwʌndəfl/",example:"We had a wonderful time.",pos:"形容词",emoji:"✨"},
{id:3017,en:"terrible",zh:"a. 可怕的；糟糕的",phonetic:"/ˈterəbl/",example:"The weather is terrible today.",pos:"形容词",emoji:"😱"},
{id:3018,en:"breakfast",zh:"n. 早餐",phonetic:"/ˈbrekfəst/",example:"What did you have for breakfast?",pos:"名词",emoji:"🍳"},
{id:3019,en:"dinner",zh:"n. 晚餐；正餐",phonetic:"/ˈdɪnər/",example:"We're having dinner at 7.",pos:"名词",emoji:"🍽️"},
{id:3020,en:"water",zh:"n. 水",phonetic:"/ˈwɔːtər/",example:"Please give me a glass of water.",pos:"名词",emoji:"💧"},
{id:3021,en:"coffee",zh:"n. 咖啡",phonetic:"/ˈkɒfi/",example:"I need a cup of coffee.",pos:"名词",emoji:"☕"},
{id:3022,en:"weather",zh:"n. 天气",phonetic:"/ˈweðər/",example:"The weather is sunny today.",pos:"名词",emoji:"☀️"},
{id:3023,en:"travel",zh:"v./n. 旅行",phonetic:"/ˈtrævl/",example:"I love to travel around the world.",pos:"动/名词",emoji:"✈️"},
{id:3024,en:"music",zh:"n. 音乐",phonetic:"/ˈmjuːzɪk/",example:"Music makes me feel relaxed.",pos:"名词",emoji:"🎵"},
{id:3025,en:"movie",zh:"n. 电影",phonetic:"/ˈmuːvi/",example:"Let's watch a movie tonight.",pos:"名词",emoji:"🎬"},
{id:3026,en:"book",zh:"n. 书",phonetic:"/bʊk/",example:"I'm reading an interesting book.",pos:"名词",emoji:"📖"},
{id:3027,en:"computer",zh:"n. 电脑",phonetic:"/kəmˈpjuːtər/",example:"I work on a computer all day.",pos:"名词",emoji:"💻"},
{id:3028,en:"phone",zh:"n. 电话；手机",phonetic:"/fəʊn/",example:"My phone is ringing.",pos:"名词",emoji:"📱"},
{id:3029,en:"money",zh:"n. 钱",phonetic:"/ˈmʌni/",example:"How much money do you need?",pos:"名词",emoji:"💰"},
{id:3030,en:"work",zh:"v./n. 工作",phonetic:"/wɜːk/",example:"I usually work from 9 to 5.",pos:"动/名词",emoji:"💼"},
{id:3031,en:"study",zh:"v./n. 学习",phonetic:"/ˈstʌdi/",example:"I study English every day.",pos:"动/名词",emoji:"📚"},
{id:3032,en:"exercise",zh:"n./v. 锻炼",phonetic:"/ˈeksəsaɪz/",example:"Regular exercise keeps you healthy.",pos:"名/动词",emoji:"🏃"},
{id:3033,en:"sleep",zh:"v./n. 睡觉",phonetic:"/sliːp/",example:"I need to get enough sleep.",pos:"动/名词",emoji:"😴"},
{id:3034,en:"cook",zh:"v. 烹饪 n. 厨师",phonetic:"/kʊk/",example:"She cooks dinner every evening.",pos:"动/名词",emoji:"👨‍🍳"},
{id:3035,en:"drive",zh:"v. 驾驶",phonetic:"/draɪv/",example:"Can you drive me to the airport?",pos:"动词",emoji:"🚗"},
{id:3036,en:"walk",zh:"v./n. 步行",phonetic:"/wɔːk/",example:"Let's take a walk in the park.",pos:"动/名词",emoji:"🚶"},
{id:3037,en:"talk",zh:"v./n. 谈话",phonetic:"/tɔːk/",example:"Can we talk about this later?",pos:"动/名词",emoji:"💬"},
{id:3038,en:"listen",zh:"v. 听",phonetic:"/ˈlɪsn/",example:"Listen carefully to the instructions.",pos:"动词",emoji:"👂"},
{id:3039,en:"watch",zh:"v. 观看 n. 手表",phonetic:"/wɒtʃ/",example:"I like to watch football on TV.",pos:"动/名词",emoji:"⌚"},
{id:3040,en:"read",zh:"v. 阅读",phonetic:"/riːd/",example:"I read the newspaper every morning.",pos:"动词",emoji:"📰"},
{id:3041,en:"write",zh:"v. 写",phonetic:"/raɪt/",example:"Please write your name here.",pos:"动词",emoji:"✍️"},
{id:3042,en:"think",zh:"v. 思考；认为",phonetic:"/θɪŋk/",example:"What do you think about this?",pos:"动词",emoji:"🤔"},
{id:3043,en:"remember",zh:"v. 记住",phonetic:"/rɪˈmembər/",example:"I can't remember his name.",pos:"动词",emoji:"🧠"},
{id:3044,en:"forget",zh:"v. 忘记",phonetic:"/fəˈɡet/",example:"Don't forget to lock the door.",pos:"动词",emoji:"🙈"},
{id:3045,en:"understand",zh:"v. 理解",phonetic:"/ˌʌndəˈstænd/",example:"Do you understand the question?",pos:"动词",emoji:"💡"},
{id:3046,en:"believe",zh:"v. 相信",phonetic:"/bɪˈliːv/",example:"I believe in you.",pos:"动词",emoji:"🙏"},
{id:3047,en:"agree",zh:"v. 同意",phonetic:"/əˈɡriː/",example:"I agree with your opinion.",pos:"动词",emoji:"👍"},
{id:3048,en:"decide",zh:"v. 决定",phonetic:"/dɪˈsaɪd/",example:"We need to decide soon.",pos:"动词",emoji:"✅"},
{id:3049,en:"choose",zh:"v. 选择",phonetic:"/tʃuːz/",example:"Choose the one you like best.",pos:"动词",emoji:"🔘"},
{id:3050,en:"prefer",zh:"v. 更喜欢",phonetic:"/prɪˈfɜːr/",example:"I prefer tea to coffee.",pos:"动词",emoji:"☕"},
{id:3051,en:"love",zh:"v./n. 爱；热爱",phonetic:"/lʌv/",example:"I love learning new things.",pos:"动/名词",emoji:"❤️"},
{id:3052,en:"hate",zh:"v. 讨厌；憎恨",phonetic:"/heɪt/",example:"I hate getting up early.",pos:"动词",emoji:"😠"},
{id:3053,en:"hope",zh:"v./n. 希望",phonetic:"/həʊp/",example:"I hope to see you soon.",pos:"动/名词",emoji:"🙏"},
{id:3054,en:"wish",zh:"v./n. 愿望；希望",phonetic:"/wɪʃ/",example:"I wish you good luck.",pos:"动/名词",emoji:"⭐"},
{id:3055,en:"dream",zh:"n./v. 梦；梦想",phonetic:"/driːm/",example:"I have a dream.",pos:"名/动词",emoji:"💭"},
{id:3056,en:"smile",zh:"v./n. 微笑",phonetic:"/smaɪl/",example:"She smiled at me.",pos:"动/名词",emoji:"😊"},
{id:3057,en:"laugh",zh:"v./n. 笑",phonetic:"/lɑːf/",example:"We laughed at the joke.",pos:"动/名词",emoji:"😂"},
{id:3058,en:"cry",zh:"v./n. 哭",phonetic:"/kraɪ/",example:"The baby started to cry.",pos:"动/名词",emoji:"😢"},
{id:3059,en:"worry",zh:"v./n. 担心",phonetic:"/ˈwʌri/",example:"Don't worry about me.",pos:"动/名词",emoji:"😟"},
{id:3060,en:"surprise",zh:"n./v. 惊喜；惊讶",phonetic:"/səˈpraɪz/",example:"What a nice surprise!",pos:"名/动词",emoji:"😲"},
{id:3061,en:"relax",zh:"v. 放松",phonetic:"/rɪˈlæks/",example:"Relax and enjoy the moment.",pos:"动词",emoji:"😌"},
{id:3062,en:"enjoy",zh:"v. 享受；喜欢",phonetic:"/ɪnˈdʒɔɪ/",example:"Did you enjoy the show?",pos:"动词",emoji:"😄"},
{id:3063,en:"expect",zh:"v. 期望；预期",phonetic:"/ɪkˈspekt/",example:"I expect to arrive by 5.",pos:"动词",emoji:"🤞"},
{id:3064,en:"promise",zh:"v./n. 承诺",phonetic:"/ˈprɒmɪs/",example:"I promise to be on time.",pos:"动/名词",emoji:"🤝"},
{id:3065,en:"refuse",zh:"v. 拒绝",phonetic:"/rɪˈfjuːz/",example:"She refused to answer.",pos:"动词",emoji:"✋"},
{id:3066,en:"accept",zh:"v. 接受",phonetic:"/əkˈsept/",example:"I accept your apology.",pos:"动词",emoji:"✅"},
{id:3067,en:"offer",zh:"v./n. 提供",phonetic:"/ˈɒfər/",example:"He offered me a job.",pos:"动/名词",emoji:"🤲"},
{id:3068,en:"suggest",zh:"v. 建议",phonetic:"/səˈdʒest/",example:"I suggest we start early.",pos:"动词",emoji:"💡"},
{id:3069,en:"explain",zh:"v. 解释",phonetic:"/ɪkˈspleɪn/",example:"Can you explain that again?",pos:"动词",emoji:"🗣️"},
{id:3070,en:"compare",zh:"v. 比较",phonetic:"/kəmˈpeər/",example:"Compare the two options.",pos:"动词",emoji:"⚖️"},
{id:3071,en:"share",zh:"v. 分享",phonetic:"/ʃeər/",example:"Let me share my experience.",pos:"动词",emoji:"🔗"},
{id:3072,en:"change",zh:"v./n. 改变",phonetic:"/tʃeɪndʒ/",example:"Things change over time.",pos:"动/名词",emoji:"🔄"},
{id:3073,en:"improve",zh:"v. 提高；改善",phonetic:"/ɪmˈpruːv/",example:"I want to improve my English.",pos:"动词",emoji:"📈"},
{id:3074,en:"develop",zh:"v. 发展；开发",phonetic:"/dɪˈveləp/",example:"The city developed quickly.",pos:"动词",emoji:"🌱"},
{id:3075,en:"continue",zh:"v. 继续",phonetic:"/kənˈtɪnjuː/",example:"Please continue with your story.",pos:"动词",emoji:"▶️"},
{id:3076,en:"follow",zh:"v. 跟随；遵守",phonetic:"/ˈfɒləʊ/",example:"Follow the instructions.",pos:"动词",emoji:"👣"},
{id:3077,en:"lead",zh:"v. 领导；引导",phonetic:"/liːd/",example:"She leads the team.",pos:"动词",emoji:"👩‍💼"},
{id:3078,en:"meet",zh:"v. 遇见；会面",phonetic:"/miːt/",example:"Nice to meet you.",pos:"动词",emoji:"🤝"},
{id:3079,en:"send",zh:"v. 发送",phonetic:"/send/",example:"I'll send you an email.",pos:"动词",emoji:"📧"},
{id:3080,en:"receive",zh:"v. 收到",phonetic:"/rɪˈsiːv/",example:"I received your message.",pos:"动词",emoji:"📬"},
{id:3081,en:"lose",zh:"v. 丢失；输掉",phonetic:"/luːz/",example:"Don't lose your keys.",pos:"动词",emoji:"🔑"},
{id:3082,en:"find",zh:"v. 找到",phonetic:"/faɪnd/",example:"I can't find my phone.",pos:"动词",emoji:"🔍"},
{id:3083,en:"keep",zh:"v. 保持；保留",phonetic:"/kiːp/",example:"Keep the change.",pos:"动词",emoji:"💪"},
{id:3084,en:"start",zh:"v./n. 开始",phonetic:"/stɑːt/",example:"Let's start the meeting.",pos:"动/名词",emoji:"▶️"},
{id:3085,en:"stop",zh:"v./n. 停止",phonetic:"/stɒp/",example:"Stop talking, please.",pos:"动/名词",emoji:"🛑"},
{id:3086,en:"finish",zh:"v. 完成",phonetic:"/ˈfɪnɪʃ/",example:"I finished my homework.",pos:"动词",emoji:"✅"},
{id:3087,en:"try",zh:"v./n. 尝试",phonetic:"/traɪ/",example:"Try your best.",pos:"动/名词",emoji:"💪"},
{id:3088,en:"practice",zh:"n./v. 练习",phonetic:"/ˈpræktɪs/",example:"Practice makes perfect.",pos:"名/动词",emoji:"🎯"},
{id:3089,en:"plan",zh:"n./v. 计划",phonetic:"/plæn/",example:"What's your plan for today?",pos:"名/动词",emoji:"📋"},
{id:3090,en:"prepare",zh:"v. 准备",phonetic:"/prɪˈpeər/",example:"Prepare for the exam.",pos:"动词",emoji:"📝"},
{id:3091,en:"check",zh:"v./n. 检查",phonetic:"/tʃek/",example:"Check your answers.",pos:"动/名词",emoji:"✔️"},
{id:3092,en:"search",zh:"v./n. 搜索",phonetic:"/sɜːtʃ/",example:"Search for the information online.",pos:"动/名词",emoji:"🔍"},
{id:3093,en:"save",zh:"v. 保存；拯救",phonetic:"/seɪv/",example:"Save your work frequently.",pos:"动词",emoji:"💾"},
{id:3094,en:"download",zh:"v. 下载",phonetic:"/ˌdaʊnˈləʊd/",example:"Download the app now.",pos:"动词",emoji:"📥"},
{id:3095,en:"upload",zh:"v. 上传",phonetic:"/ʌpˈləʊd/",example:"Upload the file to the server.",pos:"动词",emoji:"📤"},
{id:3096,en:"order",zh:"v./n. 命令；订单",phonetic:"/ˈɔːdər/",example:"I'd like to order a pizza.",pos:"动/名词",emoji:"🍕"},
{id:3097,en:"pay",zh:"v. 付款",phonetic:"/peɪ/",example:"Can I pay by card?",pos:"动词",emoji:"💳"},
{id:3098,en:"buy",zh:"v. 买",phonetic:"/baɪ/",example:"I want to buy a new laptop.",pos:"动词",emoji:"🛒"},
{id:3099,en:"sell",zh:"v. 卖",phonetic:"/sel/",example:"They sell fresh vegetables.",pos:"动词",emoji:"🏪"},
{id:3100,en:"question",zh:"n./v. 问题；提问",phonetic:"/ˈkwestʃən/",example:"Do you have any questions?",pos:"名/动词",emoji:"❓"}
];