import json

def gen_words(base_id, words_list):
    result = []
    for i, w in enumerate(words_list):
        result.append({
            "id": base_id + i,
            "en": w[0],
            "zh": w[1],
            "phonetic": w[2],
            "example": w[3],
            "pos": w[4],
            "emoji": w[5]
        })
    return result

cet4_raw = [
["abandon","v. 放弃；抛弃","/əˈbændən/","He abandoned his plan to travel.","动词","🚫"],
["ability","n. 能力；才能","/əˈbɪləti/","She has the ability to learn quickly.","名词","💪"],
["abroad","ad. 在国外","/əˈbrɔːd/","He dreams of studying abroad.","副词","✈️"],
["absent","a. 缺席的","/ˈæbsənt/","Tom was absent from school.","形容词","🏃"],
["absorb","v. 吸收；吸引","/əbˈzɔːb/","Plants absorb water from the soil.","动词","🧽"],
["abstract","a. 抽象的 n. 摘要","/ˈæbstrækt/","The concept is too abstract.","形/名","🎨"],
["abundant","a. 丰富的","/əˈbʌndənt/","The region has abundant resources.","形容词","🈵"],
["academic","a. 学术的","/ˌækəˈdemɪk/","She has an excellent academic record.","形容词","🎓"],
["accelerate","v. 加速","/əkˈseləreɪt/","The car accelerated on the highway.","动词","🚀"],
["access","n.通道 v.访问","/ˈækses/","Students have access to the library.","名/动","🔑"],
["accompany","v. 陪伴","/əˈkʌmpəni/","She accompanied her friend.","动词","👫"],
["accomplish","v. 完成；实现","/əˈkʌmplɪʃ/","We accomplished our mission.","动词","✅"],
["account","n. 账户；说明","/əˈkaʊnt/","He opened a bank account.","名词","🏦"],
["accurate","a. 准确的","/ˈækjərət/","The data must be accurate.","形容词","🎯"],
["achieve","v. 达到；取得","/əˈtʃiːv/","She achieved her goal.","动词","🏆"],
["acknowledge","v. 承认；确认","/əkˈnɒlɪdʒ/","He acknowledged his mistake.","动词","🙋"],
["acquire","v. 获得；习得","/əˈkwaɪər/","It takes time to acquire new skills.","动词","📥"],
["adapt","v. 适应；改编","/əˈdæpt/","Animals adapt to their environment.","动词","🦎"],
["adequate","a. 足够的","/ˈædɪkwət/","The supply is adequate.","形容词","✔️"],
["adjust","v. 调整；适应","/əˈdʒʌst/","You need to adjust the volume.","动词","⚙️"],
["admire","v. 钦佩；赞赏","/ədˈmaɪər/","I admire her courage.","动词","👏"],
["adopt","v. 采用；收养","/əˈdɒpt/","They decided to adopt a child.","动词","🤱"],
["advance","v./n. 前进；进步","/ədˈvɑːns/","Technology continues to advance.","动/名","⬆️"],
["advantage","n. 优势","/ədˈvɑːntɪdʒ/","Being bilingual is an advantage.","名词","👍"],
["affair","n. 事件；事务","/əˈfeər/","This is a private affair.","名词","📋"],
["affect","v. 影响；感动","/əˈfekt/","The weather affects my mood.","动词","💫"],
["afford","v. 负担得起","/əˈfɔːd/","I can't afford a new car.","动词","💰"],
["aggressive","a. 侵略的；好斗的","/əˈɡresɪv/","The dog became aggressive.","形容词","😠"],
["agreement","n. 协议；一致","/əˈɡriːmənt/","They reached an agreement.","名词","🤝"],
["alarm","n. 警报；闹钟","/əˈlɑːm/","The fire alarm went off.","名词","⏰"],
["alter","v. 改变；修改","/ˈɔːltər/","Nothing can alter the truth.","动词","✏️"],
["amaze","v. 使惊奇","/əˈmeɪz/","His talent amazed everyone.","动词","😲"],
["ambition","n. 野心；雄心","/æmˈbɪʃn/","She has the ambition to succeed.","名词","🔥"],
["amount","n. 数量；金额","/əˈmaʊnt/","A large amount of money.","名词","🔢"],
["analyze","v. 分析","/ˈænəlaɪz/","We need to analyze the data.","动词","🔍"],
["anniversary","n. 周年纪念日","/ˌænɪˈvɜːsəri/","Today is our anniversary.","名词","🎂"],
["announce","v. 宣布；通告","/əˈnaʊns/","The company announced new products.","动词","📣"],
["annual","a. 年度的","/ˈænjuəl/","The annual meeting is next week.","形容词","📅"],
["anxiety","n. 焦虑；忧虑","/æŋˈzaɪəti/","She suffers from anxiety.","名词","😰"],
["apparent","a. 明显的","/əˈpærənt/","It was apparent he was lying.","形容词","👀"],
["appeal","v./n. 呼吁；吸引","/əˈpiːl/","The idea appeals to young people.","动/名","📢"],
["appetite","n. 食欲；胃口","/ˈæpɪtaɪt/","Exercise gave her a good appetite.","名词","🍽️"],
["application","n. 申请；应用","/ˌæplɪˈkeɪʃn/","I submitted my job application.","名词","📝"],
["appreciate","v. 欣赏；感激","/əˈpriːʃieɪt/","I appreciate your help.","动词","🙏"],
["approach","v./n. 接近；方法","/əˈprəʊtʃ/","We need a new approach.","动/名","🚶"],
["appropriate","a. 适当的","/əˈprəʊpriət/","Is this appropriate for work?","形容词","👌"],
["approve","v. 批准；赞成","/əˈpruːv/","The plan was approved.","动词","✅"],
["argue","v. 争论；辩论","/ˈɑːɡjuː/","They argued about politics.","动词","💬"],
["arrange","v. 安排；整理","/əˈreɪndʒ/","She arranged the flowers.","动词","🌺"],
["artificial","a. 人工的","/ˌɑːtɪˈfɪʃl/","Artificial intelligence is advancing.","形容词","🤖"],
["aspect","n. 方面；层面","/ˈæspekt/","This aspect is crucial.","名词","🔲"],
["assemble","v. 集合；组装","/əˈsembl/","He assembled the furniture.","动词","🔧"],
["assess","v. 评估；评定","/əˈses/","Teachers assess progress.","动词","📊"],
["assign","v. 分配；指派","/əˈsaɪn/","The task was assigned to me.","动词","📌"],
["assist","v. 帮助；协助","/əˈsɪst/","Can I assist you?","动词","🆘"],
["associate","v. 联系；关联","/əˈsəʊʃieɪt/","People associate red with danger.","动词","🔗"],
["assume","v. 假设；承担","/əˈsjuːm/","Don't assume it will be easy.","动词","🤔"],
["atmosphere","n. 气氛；大气层","/ˈætməsfɪər/","The restaurant has a cozy atmosphere.","名词","🌍"],
["attach","v. 附上；连接","/əˈtætʃ/","Please attach the file.","动词","📎"],
["attempt","v./n. 尝试；企图","/əˈtempt/","He attempted to break the record.","动/名","🎯"],
["attend","v. 出席；参加","/əˈtend/","Will you attend the meeting?","动词","🏫"],
["attitude","n. 态度；看法","/ˈætɪtjuːd/","A positive attitude is important.","名词","😊"],
["attract","v. 吸引；引起","/əˈtrækt/","The light attracts insects.","动词","🧲"],
["authority","n. 权威；当局","/ɔːˈθɒrəti/","The authority issued new rules.","名词","👮"],
["available","a. 可用的；有空的","/əˈveɪləbl/","Is this seat available?","形容词","🟢"],
["average","n./a. 平均的","/ˈævərɪdʒ/","The average score was 85.","名/形","📈"],
["avoid","v. 避免；回避","/əˈvɔɪd/","Try to avoid rush hour.","动词","🚧"],
["aware","a. 意识到的","/əˈweər/","Are you aware of the risks?","形容词","💡"],
["balance","n./v. 平衡","/ˈbæləns/","Balance work and life.","名/动","⚖️"],
["ban","v./n. 禁止","/bæn/","Smoking is banned here.","动/名","🚫"],
["barrier","n. 障碍；屏障","/ˈbæriər/","Language can be a barrier.","名词","🧱"],
["behalf","n. 代表","/bɪˈhɑːf/","I speak on behalf of the team.","名词","🗣️"],
["behave","v. 行为；表现","/bɪˈheɪv/","Children should behave well.","动词","🧒"],
["benefit","n.利益 v.有益于","/ˈbenɪfɪt/","Exercise benefits your health.","名/动","💪"],
["bitter","a. 苦的；痛苦的","/ˈbɪtər/","The medicine tastes bitter.","形容词","😖"],
["blame","v./n. 责备","/bleɪm/","Don't blame others.","动/名","👉"],
["border","n. 边界；边境","/ˈbɔːdər/","They crossed the border.","名词","🗺️"],
["bore","v. 使厌烦","/bɔːr/","Long speeches bore me.","动词","🥱"],
["brand","n. 品牌；商标","/brænd/","This brand is popular.","名词","🏷️"],
["budget","n./v. 预算","/ˈbʌdʒɪt/","We need to budget expenses.","名/动","💵"],
["burden","n. 负担；重担","/ˈbɜːdn/","The debt is a heavy burden.","名词","🏋️"],
["campaign","n. 运动；战役","/kæmˈpeɪn/","They launched a campaign.","名词","📣"],
["capable","a. 有能力的","/ˈkeɪpəbl/","She is capable of leading.","形容词","👩‍💼"],
["capture","v. 捕获；俘获","/ˈkæptʃər/","She captured the moment.","动词","📸"],
["career","n. 职业；生涯","/kəˈrɪər/","She chose teaching as her career.","名词","💼"],
["category","n. 类别；种类","/ˈkætəɡəri/","Books are sorted by category.","名词","🗂️"],
["celebrate","v. 庆祝","/ˈselɪbreɪt/","We celebrate New Year.","动词","🎉"],
["challenge","n./v. 挑战","/ˈtʃælɪndʒ/","This is a real challenge.","动/名","🏔️"],
["characteristic","n.特征 a.特有的","/ˌkærəktəˈrɪstɪk/","What are its characteristics?","名/形","🔬"],
["circumstance","n. 环境；情况","/ˈsɜːkəmstəns/","Under no circumstance lie.","名词","🔄"],
["claim","v./n. 声称；要求","/kleɪm/","He claims to be innocent.","动/名","✋"],
["climate","n. 气候；风气","/ˈklaɪmət/","Climate change is a global issue.","名词","🌤️"],
["collapse","v./n. 倒塌；崩溃","/kəˈlæps/","The building collapsed.","动/名","💥"],
["colleague","n. 同事；同僚","/ˈkɒliːɡ/","I discussed it with my colleague.","名词","👥"],
["commerce","n. 商业；贸易","/ˈkɒmɜːs/","E-commerce is growing rapidly.","名词","🛒"],
["commit","v. 犯（罪）；承诺","/kəˈmɪt/","He committed a crime.","动词","🤝"],
["communicate","v. 交流；沟通","/kəˈmjuːnɪkeɪt/","We communicate by email.","动词","📱"],
["companion","n. 同伴；伙伴","/kəmˈpæniən/","A dog is a loyal companion.","名词","🐕"],
["comparison","n. 比较；对比","/kəmˈpærɪsn/","In comparison, this is cheaper.","名词","⚖️"],
["compensate","v. 补偿；弥补","/ˈkɒmpenseɪt/","Nothing can compensate for lost time.","动词","💱"],
["compete","v. 竞争；比赛","/kəmˈpiːt/","Athletes compete for gold.","动词","🏅"],
["complain","v. 抱怨；投诉","/kəmˈpleɪn/","He always complains.","动词","😤"],
["complex","a. 复杂的","/ˈkɒmpleks/","The problem is too complex.","形容词","🧩"],
["concentrate","v. 集中；专注","/ˈkɒnsntreɪt/","Concentrate on your studies.","动词","🧠"],
["concept","n. 概念；观念","/ˈkɒnsept/","It's a difficult concept.","名词","💭"],
["concern","n./v. 关心；担忧","/kənˈsɜːn/","This concerns all of us.","名/动","😟"],
["conclude","v. 得出结论；结束","/kənˈkluːd/","We concluded the meeting.","动词","🏁"],
["concrete","a.具体的 n.混凝土","/ˈkɒŋkriːt/","Give me a concrete example.","形/名","🧱"],
["conduct","v./n. 进行；指挥","/kənˈdʌkt/","They conducted a survey.","动/名","🎼"],
["conference","n. 会议","/ˈkɒnfərəns/","The conference attracted many.","名词","🎤"],
["confirm","v. 确认；证实","/kənˈfɜːm/","Can you confirm the booking?","动词","✔️"],
["conflict","n./v. 冲突；矛盾","/ˈkɒnflɪkt/","The conflict lasted for years.","名/动","💢"],
["conscious","a. 有意识的","/ˈkɒnʃəs/","He was conscious of the danger.","形容词","👁️"],
["consequence","n. 结果；后果","/ˈkɒnsɪkwəns/","Think about the consequences.","名词","⚡"],
["conservative","a. 保守的","/kənˈsɜːvətɪv/","She has a conservative attitude.","形容词","🛡️"],
["constant","a. 不变的；持续的","/ˈkɒnstənt/","The constant noise is annoying.","形容词","♾️"],
["construct","v. 建造；构造","/kənˈstrʌkt/","They constructed a new bridge.","动词","🏗️"],
["consume","v. 消费；消耗","/kənˈsjuːm/","This car consumes less fuel.","动词","⛽"],
["contact","n./v. 联系；接触","/ˈkɒntækt/","Please contact me by email.","名/动","📞"],
["contain","v. 包含；容纳","/kənˈteɪn/","The bottle contains water.","动词","🫙"],
["context","n. 上下文；背景","/ˈkɒntekst/","You need context to understand.","名词","📄"],
["contract","n.合同 v.收缩","/ˈkɒntrækt/","They signed a contract.","名/动","📝"],
["contribute","v. 贡献；捐献","/kənˈtrɪbjuːt/","Everyone should contribute.","动词","🤲"],
["convenient","a. 方便的","/kənˈviːniənt/","The location is convenient.","形容词","📍"],
["convince","v. 说服；使确信","/kənˈvɪns/","She convinced me to join.","动词","🗣️"],
["cooperate","v. 合作；协作","/kəʊˈɒpəreɪt/","Let's cooperate to finish this.","动词","🤝"],
["crash","v./n. 碰撞；崩溃","/kræʃ/","The computer crashed.","动/名","💥"],
["create","v. 创造；创建","/kriˈeɪt/","Artists create beautiful works.","动词","✨"],
["crime","n. 犯罪；罪行","/kraɪm/","Crime rates have decreased.","名词","🔒"],
["crisis","n. 危机","/ˈkraɪsɪs/","The company faced a crisis.","名词","🚨"],
["critical","a. 批评的；关键的","/ˈkrɪtɪkl/","This is a critical decision.","形容词","⚠️"],
["crucial","a. 至关重要的","/ˈkruːʃl/","Time is crucial in emergencies.","形容词","❗"],
["cultivate","v. 培养；耕作","/ˈkʌltɪveɪt/","Cultivate a good habit.","动词","🌱"],
["curiosity","n. 好奇心","/ˌkjʊəriˈɒsəti/","Curiosity drives discovery.","名词","🐱"],
["current","a.当前的 n.水流","/ˈkʌrənt/","What is the current situation?","形/名","⚡"],
["debate","n./v. 辩论；争论","/dɪˈbeɪt/","The topic sparked debate.","名/动","🎤"],
["decade","n. 十年","/ˈdekeɪd/","The city changed over a decade.","名词","📅"],
["decline","v./n. 下降；拒绝","/dɪˈklaɪn/","Sales declined by 10 percent.","动/名","📉"],
["define","v. 定义；界定","/dɪˈfaɪn/","How do you define happiness?","动词","📖"],
["deliberate","a. 故意的","/dɪˈlɪbərət/","It was a deliberate decision.","形容词","🤔"],
["deliver","v. 递送；发表","/dɪˈlɪvər/","The package was delivered.","动词","📦"],
["demand","n./v. 要求；需求","/dɪˈmɑːnd/","Demand for water is increasing.","名/动","📈"],
["demonstrate","v. 展示；证明","/ˈdemənstreɪt/","He demonstrated the product.","动词","👨‍🏫"],
["depend","v. 依赖；取决于","/dɪˈpend/","It depends on the weather.","动词","🔗"],
["describe","v. 描述；形容","/dɪˈskraɪb/","Can you describe the suspect?","动词","✍️"],
["deserve","v. 值得；应得","/dɪˈzɜːv/","You deserve a reward.","动词","🏆"],
["desperate","a. 绝望的","/ˈdespərət/","He was desperate for help.","形容词","😱"],
["destination","n. 目的地","/ˌdestɪˈneɪʃn/","We arrived at our destination.","名词","📍"],
["determine","v. 决定；确定","/dɪˈtɜːmɪn/","We need to determine the cause.","动词","🎯"],
["device","n. 设备；装置","/dɪˈvaɪs/","This device saves energy.","名词","📱"],
["devote","v. 致力于；奉献","/dɪˈvəʊt/","She devoted her life to education.","动词","❤️"],
["dilemma","n. 困境；进退两难","/daɪˈlemə/","He faced a moral dilemma.","名词","😖"],
["discipline","n. 纪律；学科","/ˈdɪsəplɪn/","Self-discipline is key.","名词","📏"],
["discount","n.折扣 v.打折","/ˈdɪskaʊnt/","They offered a discount.","名/动","🏷️"],
["display","v./n. 展示；显示","/dɪˈspleɪ/","The works are on display.","动/名","🖥️"],
["distinct","a. 明显的；不同的","/dɪˈstɪŋkt/","There is a distinct smell.","形容词","🔍"],
["distribute","v. 分配；分发","/dɪˈstrɪbjuːt/","Food was distributed.","动词","📬"],
["diverse","a. 多样的；不同的","/daɪˈvɜːs/","The city has a diverse culture.","形容词","🌈"],
["document","n.文件 v.记录","/ˈdɒkjumənt/","Please sign this document.","名/动","📄"],
["domestic","a. 国内的；家庭的","/dəˈmestɪk/","Domestic flights are cheaper.","形容词","🏠"],
["dominate","v. 支配；统治","/ˈdɒmɪneɪt/","The team dominates the league.","动词","👑"],
["dramatic","a. 戏剧性的；巨大的","/drəˈmætɪk/","There was a dramatic change.","形容词","🎭"],
["economy","n. 经济；节约","/ɪˈkɒnəmi/","The economy is growing.","名词","📊"],
["educate","v. 教育；培养","/ˈedʒukeɪt/","Parents educate their children.","动词","📚"],
["efficient","a. 高效的","/ɪˈfɪʃnt/","This method is efficient.","形容词","⚡"],
["eliminate","v. 消除；淘汰","/ɪˈlɪmɪneɪt/","We must eliminate poverty.","动词","🗑️"],
["embrace","v. 拥抱；欣然接受","/ɪmˈbreɪs/","Embrace new challenges.","动词","🤗"],
["emerge","v. 出现；浮现","/ɪˈmɜːdʒ/","New evidence emerged.","动词","🌅"],
["emotion","n. 情感；情绪","/ɪˈməʊʃn/","She showed no emotion.","名词","❤️"],
["emphasis","n. 强调；重点","/ˈemfəsɪs/","The emphasis is on quality.","名词","❗"],
["employ","v. 雇用；使用","/ɪmˈplɔɪ/","The company employs 500 people.","动词","👔"],
["enable","v. 使能够；启用","/ɪˈneɪbl/","This key enables the function.","动词","🔓"],
["encounter","v./n. 遭遇；邂逅","/ɪnˈkaʊntər/","We encountered many problems.","动/名","⚡"],
["engage","v. 从事；吸引","/ɪnˈɡeɪdʒ/","She is engaged in research.","动词","🔬"],
["enormous","a. 巨大的；庞大的","/ɪˈnɔːməs/","The cost is enormous.","形容词","🐘"],
["ensure","v. 确保；保证","/ɪnˈʃʊər/","Please ensure the door is locked.","动词","🔒"],
["enterprise","n. 企业；事业","/ˈentəpraɪz/","He started his own enterprise.","名词","🏢"],
["enthusiasm","n. 热情；热忱","/ɪnˈθjuːziæzəm/","She showed great enthusiasm.","名词","🔥"],
["environment","n. 环境","/ɪnˈvaɪrənmənt/","Protect the environment.","名词","🌍"],
["establish","v. 建立；设立","/ɪˈstæblɪʃ/","They established a new company.","动词","🏗️"],
["evaluate","v. 评价；评估","/ɪˈvæljueɪt/","We need to evaluate the results.","动词","📝"],
["evidence","n. 证据；证明","/ˈevɪdəns/","There is no evidence.","名词","🔍"],
["evolve","v. 进化；发展","/ɪˈvɒlv/","Species evolve over time.","动词","🧬"],
["examine","v. 检查；考试","/ɪɡˈzæmɪn/","The doctor examined the patient.","动词","🔬"],
["exception","n. 例外","/ɪkˈsepʃn/","There is no exception.","名词","➖"],
["exhaust","v.使精疲力尽 n.废气","/ɪɡˈzɔːst/","The work exhausted me.","动/名","😫"],
["expand","v. 扩展；膨胀","/ɪkˈspænd/","The business is expanding.","动词","🔍"],
["experiment","n./v. 实验；试验","/ɪkˈsperɪmənt/","The experiment was successful.","名/动","🧪"],
["expert","n.专家 a.熟练的","/ˈekspɜːt/","She is an expert in finance.","名/形","👩‍🔬"],
["export","v./n. 出口；输出","/ɪkˈspɔːt/","The country exports oil.","动/名","🚢"],
["external","a. 外部的","/ɪkˈstɜːnl/","External factors affected it.","形容词","🌐"],
["extraordinary","a. 非凡的；特别的","/ɪkˈstrɔːdnri/","She has extraordinary talent.","形容词","🌟"],
["facility","n. 设施；设备","/fəˈsɪləti/","The sports facility is great.","名词","🏟️"],
["faith","n. 信仰；信心","/feɪθ/","Have faith in yourself.","名词","🙏"],
["feature","n.特征 v.以…为特色","/ˈfiːtʃər/","This phone has many features.","名/动","✨"],
["finance","n.财政 v.资助","/ˈfaɪnæns/","He works in finance.","名/动","💹"],
["flexible","a. 灵活的；柔韧的","/ˈfleksəbl/","We need a flexible schedule.","形容词","🤸"],
["focus","n./v. 焦点；集中","/ˈfəʊkəs/","Focus on your goals.","名/动","🔍"],
["former","a. 前者的；以前的","/ˈfɔːmər/","The former president gave a speech.","形容词","⬅️"],
["fortune","n. 财富；运气","/ˈfɔːtʃuːn/","She made a fortune in business.","名词","💎"],
["fulfill","v. 实现；履行","/fʊlˈfɪl/","He fulfilled his dream.","动词","🌟"],
["function","n.功能 v.运转","/ˈfʌŋkʃn/","What is the function of this button?","名/动","⚙️"],
["fundamental","a. 基本的；根本的","/ˌfʌndəˈmentl/","This is a fundamental principle.","形容词","🔑"],
["generate","v. 产生；生成","/ˈdʒenəreɪt/","The wind can generate electricity.","动词","⚡"],
["generous","a. 慷慨的；大方的","/ˈdʒenərəs/","She is generous with her time.","形容词","🎁"],
["genuine","a. 真正的；真诚的","/ˈdʒenjuɪn/","It was a genuine mistake.","形容词","💯"],
["global","a. 全球的；总体的","/ˈɡləʊbl/","Global warming is a serious issue.","形容词","🌏"],
["gradual","a. 逐渐的；渐进的","/ˈɡrædʒuəl/","There was a gradual improvement.","形容词","🐢"],
["guarantee","n./v. 保证；担保","/ˌɡærənˈtiː/","We guarantee the quality.","名/动","🛡️"],
["guidance","n. 指导；引导","/ˈɡaɪdns/","She needs guidance from a mentor.","名词","🧭"],
["handle","v.处理 n.手柄","/ˈhændl/","Can you handle this problem?","动/名","🤲"],
["identify","v. 识别；鉴定","/aɪˈdentɪfaɪ/","Can you identify the plant?","动词","🔎"],
["ignore","v. 忽视；不理睬","/ɪɡˈnɔːr/","Don't ignore the warning signs.","动词","🙈"],
["illustrate","v. 说明；阐明","/ˈɪləstreɪt/","Let me illustrate with an example.","动词","🖼️"],
["impact","n./v. 影响；冲击","/ˈɪmpækt/","The impact of the news was huge.","名/动","💥"],
["implement","v. 实施；执行","/ˈɪmplɪment/","We need to implement the plan.","动词","🔨"],
["implication","n. 含义；暗示","/ˌɪmplɪˈkeɪʃn/","What are the implications of this?","名词","💡"],
["impose","v. 强加；征收","/ɪmˈpəʊz/","Don't impose your views on others.","动词","📜"],
["impress","v. 留下印象","/ɪmˈpres/","His speech impressed me deeply.","动词","🌟"],
["incident","n. 事件；事变","/ˈɪnsɪdənt/","The incident was reported to police.","名词","📰"],
["incline","v. 倾向；倾斜","/ɪnˈklaɪn/","I incline to agree with you.","动词","📐"],
["income","n. 收入；收益","/ˈɪnkʌm/","He has a stable income.","名词","💵"],
["independent","a. 独立的","/ˌɪndɪˈpendənt/","She is very independent.","形容词","🆓"],
["indicate","v. 表明；指示","/ˈɪndɪkeɪt/","The sign indicates the direction.","动词","👉"],
["individual","n./a. 个人；个体的","/ˌɪndɪˈvɪdʒuəl/","Each individual is unique.","名/形","👤"],
["industry","n. 工业；行业","/ˈɪndəstri/","The automobile industry is booming.","名词","🏭"],
["influence","n./v. 影响","/ˈɪnfluəns/","Her influence on me is profound.","名/动","💫"],
["inform","v. 通知；告知","/ɪnˈfɔːm/","Please inform me of any changes.","动词","📧"],
["initial","a. 最初的；开始的","/ɪˈnɪʃl/","The initial plan was changed.","形容词","🔰"],
["initiative","n. 主动性；倡议","/ɪˈnɪʃətɪv/","Take the initiative to help.","名词","🏃"],
["innovation","n. 创新；革新","/ˌɪnəˈveɪʃn/","Innovation drives progress.","名词","💡"],
["inquiry","n. 询问；调查","/ɪnˈkwaɪəri/","The police made an inquiry.","名词","🔍"],
["inspire","v. 激励；启发","/ɪnˈspaɪər/","Her story inspired many people.","动词","💫"],
["install","v. 安装；安置","/ɪnˈstɔːl/","We need to install new software.","动词","💻"],
["instance","n. 实例；情况","/ˈɪnstəns/","For instance, let me explain.","名词","📌"],
["instrument","n. 工具；乐器","/ˈɪnstrəmənt/","The piano is a musical instrument.","名词","🎹"],
["insurance","n. 保险","/ɪnˈʃʊərəns/","You need health insurance.","名词","🛡️"],
["intellectual","a. 智力的","/ˌɪntəˈlektʃuəl/","She is an intellectual person.","形容词","🧠"],
["intelligence","n. 智力；情报","/ɪnˈtelɪdʒəns/","Artificial intelligence is growing.","名词","🤖"],
["intense","a. 强烈的；激烈的","/ɪnˈtens/","The competition was intense.","形容词","🔥"],
["intention","n. 意图；目的","/ɪnˈtenʃn/","That was not my intention.","名词","🎯"],
["interact","v. 互动；相互作用","/ˌɪntərˈækt/","Children learn by interacting.","动词","🤝"],
["interpret","v. 解释；口译","/ɪnˈtɜːprɪt/","How do you interpret this poem?","动词","🗣️"],
["interval","n. 间隔；休息","/ˈɪntəvl/","Take a short interval between study.","名词","⏸️"],
["invest","v. 投资；投入","/ɪnˈvest/","Invest time in learning.","动词","📈"],
["investigate","v. 调查；研究","/ɪnˈvestɪɡeɪt/","Police are investigating the case.","动词","🕵️"],
["involve","v. 涉及；包含","/ɪnˈvɒlv/","The job involves travel.","动词","🔗"],
["isolate","v. 隔离；孤立","/ˈaɪsəleɪt/","The patient was isolated.","动词","🏝️"],
["issue","n./v. 问题；议题","/ˈɪʃuː/","This is a serious issue.","名/动","⚠️"],
["item","n. 项目；物品","/ˈaɪtəm/","Check each item on the list.","名词","📋"],
["journal","n. 期刊；日记","/ˈdʒɜːnl/","She keeps a daily journal.","名词","📓"],
["judgment","n. 判断；审判","/ˈdʒʌdʒmənt/","Make your own judgment.","名词","⚖️"],
["justice","n. 正义；公正","/ˈdʒʌstɪs/","We fight for justice.","名词","⚖️"],
["justify","v. 证明…正当","/ˈdʒʌstɪfaɪ/","How can you justify your actions?","动词","✅"],
["keen","a. 热切的；渴望的","/kiːn/","She is keen to learn.","形容词","🔥"],
["knowledge","n. 知识；学问","/ˈnɒlɪdʒ/","Knowledge is power.","名词","📚"],
["label","n./v. 标签；标注","/ˈleɪbl/","Read the label carefully.","名/动","🏷️"],
["landscape","n. 风景；景观","/ˈlændskeɪp/","The landscape is beautiful.","名词","🏞️"],
["launch","v. 发射；发起","/lɔːntʃ/","They launched a new product.","动词","🚀"],
["leading","a. 主要的；领先的","/ˈliːdɪŋ/","She is a leading expert.","形容词","🥇"],
["legislation","n. 立法；法规","/ˌledʒɪsˈleɪʃn/","New legislation was passed.","名词","📜"],
["locate","v. 定位；位于","/ləʊˈkeɪt/","Can you locate the city on the map?","动词","📍"],
["logic","n. 逻辑；推理","/ˈlɒdʒɪk/","There is no logic in his argument.","名词","🧮"],
["maintain","v. 维持；保养","/meɪnˈteɪn/","Maintain a healthy lifestyle.","动词","🔧"],
["majority","n. 大多数","/məˈdʒɒrəti/","The majority agreed with the plan.","名词","👥"],
["manufacture","v./n. 制造；生产","/ˌmænjuˈfæktʃər/","They manufacture electronic parts.","动/名","🏭"],
["mature","a. 成熟的","/məˈtʃʊər/","He is very mature for his age.","形容词","🧓"],
["mechanism","n. 机制；机械装置","/ˈmekənɪzəm/","The mechanism works smoothly.","名词","⚙️"],
["medium","n.媒介 a.中等的","/ˈmiːdiəm/","Television is a powerful medium.","名/形","📺"],
["mental","a. 精神的；心理的","/ˈmentl/","Mental health is important.","形容词","🧠"],
["minor","a. 较小的；次要的","/ˈmaɪnər/","It's a minor problem.","形容词","🔽"],
["mission","n. 任务；使命","/ˈmɪʃn/","Our mission is to help others.","名词","🎯"],
["modify","v. 修改；调整","/ˈmɒdɪfaɪ/","We need to modify the plan.","动词","✏️"],
["monitor","v./n. 监控；监视器","/ˈmɒnɪtər/","They monitor the system 24/7.","动/名","🖥️"],
["mood","n. 情绪；心情","/muːd/","She is in a good mood.","名词","😊"],
["moral","a.道德的 n.寓意","/ˈmɒrəl/","It's a moral issue.","形/名","⚖️"],
["motion","n. 运动；动议","/ˈməʊʃn/","The car was in motion.","名词","🏃"],
["motivate","v. 激励；激发","/ˈməʊtɪveɪt/","What motivates you to work hard?","动词","💪"],
["negative","a. 消极的；负面的","/ˈneɡətɪv/","Don't be so negative.","形容词","👎"],
["neglect","v./n. 忽视；疏忽","/nɪˈɡlekt/","Don't neglect your health.","动/名","🙈"],
["negotiate","v. 谈判；协商","/nɪˈɡəʊʃieɪt/","They negotiated a peace deal.","动词","🤝"],
["network","n./v. 网络","/ˈnetwɜːk/","Social networks connect people.","名/动","🌐"],
["neutral","a. 中立的","/ˈnjuːtrəl/","Switzerland remained neutral.","形容词","⚪"],
["normal","a. 正常的；标准的","/ˈnɔːml/","Everything is back to normal.","形容词","✅"],
["notion","n. 概念；观念","/ˈnəʊʃn/","I have no notion of what to do.","名词","💭"],
["numerous","a. 许多的；大量的","/ˈnjuːmərəs/","Numerous people attended.","形容词","🔢"],
["objective","n.目标 a.客观的","/əbˈdʒektɪv/","Set clear objectives for yourself.","名/形","🎯"],
["obligation","n. 义务；责任","/ˌɒblɪˈɡeɪʃn/","You have an obligation to tell the truth.","名词","📜"],
["observation","n. 观察；评论","/ˌɒbzəˈveɪʃn/","His observation was accurate.","名词","🔍"],
["obstacle","n. 障碍；阻碍","/ˈɒbstəkl/","Lack of money is an obstacle.","名词","🚧"],
["obtain","v. 获得；得到","/əbˈteɪn/","Where can I obtain a ticket?","动词","🎫"],
["obvious","a. 明显的","/ˈɒbviəs/","The answer is obvious.","形容词","👀"],
["occasion","n. 场合；时机","/əˈkeɪʒn/","On this special occasion...","名词","🎊"],
["occupy","v. 占据；使忙碌","/ˈɒkjupaɪ/","Reading occupies most of my time.","动词","📖"],
["occur","v. 发生；出现","/əˈkɜːr/","Accidents occur every day.","动词","⚡"],
["official","a./n. 官方的；官员","/əˈfɪʃl/","This is an official statement.","形/名","🏛️"],
["operate","v. 操作；经营","/ˈɒpəreɪt/","He knows how to operate the machine.","动词","⚙️"],
["opponent","n. 对手；反对者","/əˈpəʊnənt/","He defeated his opponent.","名词","🥊"],
["opportunity","n. 机会；时机","/ˌɒpəˈtjuːnəti/","This is a great opportunity.","名词","🚪"],
["oppose","v. 反对；对抗","/əˈpəʊz/","They oppose the new law.","动词","✋"],
["optimistic","a. 乐观的","/ˌɒptɪˈmɪstɪk/","She is optimistic about the future.","形容词","😊"],
["option","n. 选择；选项","/ˈɒpʃn/","You have several options.","名词","🔘"],
["ordinary","a. 普通的；平凡的","/ˈɔːdnri/","It was just an ordinary day.","形容词","📅"],
["organize","v. 组织；安排","/ˈɔːɡənaɪz/","She organized the party.","动词","📋"],
["origin","n. 起源；出身","/ˈɒrɪdʒɪn/","What is the origin of this word?","名词","🌱"],
["otherwise","ad. 否则；另外","/ˈʌðəwaɪz/","Hurry up, otherwise we'll be late.","副词","⚠️"],
["outcome","n. 结果；